### ISSUE TITLE
NETMF (micro framework) support

### ISSUE THREAD

**Issue by aquaseal** [SignalR/SignalR#186]
server side support for netmf devices. would be very useful to have a netmf device push data to a client in near real time. not sure if client side support would be useful.

**Comment by PaulSch** [comment]
Hi Brandon,

Did you ever get round to suplementing SignalR with MQTT?
It sounds like an interresting solution...

Regards,
Paul

**Comment by brbarnett** [comment]
Unfortunately not. These days, I don't really even think SignalR would be the answer.  

Best: https://azure.microsoft.com/en-us/services/iot-hub/
Works: https://azure.microsoft.com/en-us/services/service-bus/

Both of these would be better than using SignalR here, in my opinion.  IoT Hub represents an environment where a device can register itself and set up pub/sub to which you can push messages.  Service Bus can have the same effect, but not managed by device...it'd more be a pub/sub to a queue or topic that's specific to the device's unique ID (serial).

There are other solutions out there, of course, but my background is in Azure so that's where I tend to gravitate :)
