### ISSUE TITLE
Hub OnConnected/OnDisconnected methods are not called when a Javascript client doesn't define any callable methods

### ISSUE THREAD

**Issue by AdamFreeman** [SignalR/SignalR#2036]
If the client doesn't attach any functions to  via the hub.client object, then the URL used to open the transport connection omits the ConnectionData value from the query string.

The result is that the OnConnected and OnDisconnected methods in the server-side Hub class are not called when the client connects and disconnects. Other operations work fine - the client can call methods on the sever and get a result, for example.

**Comment by davidfowl** [comment]
How would that work? Fire the callback on all hubs all the time?

**Comment by Sebastriani** [comment]
Sorry I don't understand what you mean by "Fire the callback on all hubs all the time", I don't see the need to do that because of what I'm talking about. There's probably some technical aspect I'm not understanding.

I'm using a jQuery Javascript client that just needs to call server methods and needs no client callback methods other than the deferred.done and deferred.fail from jQuery.

To perform some actions, I just need OnConnected to be fired on the server when I execute a server method, I don't see where's the need to "Fire the callback on all the hubs all the time", I just don't get it. What does that have to do with triggering OnConnected when executing a server method and not having any client method declared??

AuthorizeHubConnection and AuthorizeHubMethodInvocation from AuthorizeAttribute are being fired even if there's no client methods declared so, how come it's no possible to do the same for OnConnected? Why you need a client method declared to know what Hub you need to fire the OnConnectedd on if you don't need a client method to know when to fire and Authorize callback. 

I know that you are declaring the Attributes on the Hubs or methods themselves on the server but they are even called before the OnConnected event so, if you already know what Hub I am connecting to, to be able to fire the AuthorizeAttribute methods even before calling the OnConnected, how come can you not know what Hub you need to trigger the OnConnected event on, if you already have that information beforhand?

It's absolutelly counterintuitive for me (and some others it seems) that OnConnected is not being fired on the server when you have no client methods declared. 

The workaround is simple, I just declare a dummy client method and that's it, but that's just a hack and I've been hours trying to understand why the OnConnected wasn't being called.

I don't know, probably that's something really difficult to do but if that's just "by design" could you change that behavour it in an upcoming release? Believe me it's useful.

Don't get me wrong, I think SingalR is a really useful and awesome tool but I just don't get this.

Regards.

**Comment by davidfowl** [comment]
It’s a quirk of multiplexing all hubs over a single connection, we have to know what hubs you care about and that’s done by looking at callbacks registered for specific hubs. 

> I don't know, probably that's something really difficult to do but if that's just "by design" could you change that behavour it in an upcoming release? Believe me it's useful.

No. We don’t have any plans to make a change this big in a point release. This version of SignalR is in bug fix mode. While this could be considered a “bug fix”, it’s major breaking change that will likely have a tail. 

Also the behavior has been this way since the beginning and while it’s unintuitive, it’s easy to work around. 

ASP.NET Core SignalR doesn’t have this quirk mostly becuse we avoided supporting untold hubs per connection as a design point.

**Comment by Sebastriani** [comment]
Ok thanks, I don't know how come I didn't see before the Note about this subject in the documentation from the link you provided 5 years ago, my fault... I found the solution elsewhere and it took me hours to get around this. 

Anyway, that's an odd behaviour that I'm courious about, I'll try to get through the code when I have time, to see if I manage to understand it.

Regards

**Comment by mbpakalin** [comment]
I'm having the same problem. Can you share your code with me ?
