### ISSUE TITLE
Losing messages from server to client

### ISSUE THREAD

**Issue by mkuzminski** [SignalR/SignalR#2075]
I have a fairly simply test where I self host a signalR hub connection in a windows console program to send "TerminalRequest" objects to my connected clients. Both the server console and the client console are running on the same machine. The TerminalRequest object is comprised of a few properties and string property which contains a base64 encoded image. The size of the image is 64,892 bytes.

When I loop over sending all my connected clients a TerminalRequest (tr in code below) the server sends the items, but the client drops some. 

[ServerCode]

```
 var context = GlobalHost.ConnectionManager.GetHubContext("myHub");
 for (int i = 1;i<= 100000; i++)
                    {
                        Console.WriteLine("Sending item: " + i);
                        context.Clients.All.ProcessTerminalRequest(tr);
                    }
```

With LongPolling Transport the server Server Sends 100,000 and then the client stops receiving at count 67000. This actually fluctuates depending on how fast the server gets done looping through sending the items.

```
  public static void OutputTerminalRequest(TerminalRequest tr)
        {
            lock (lockobject)
            {
                TOTAL_RECEIVED_COUNT++;
                Console.WriteLine("Total Count Received: " + TOTAL_RECEIVED_COUNT);

            }
        }
```

[ClientCode]

```
 myHub.On<TerminalRequest>("ProcessTerminalRequest", tr => OutputTerminalRequest(tr));
```

It seems that as soon as the Server stops sending in the loop, the client immediate stops receiving/counting up the number of transactions. This makes it appear like it is dropping messages between the server and client as the total sent from the server doesn't match the total received. 

This happens for LongPolling, ServerSentEvents. Can't use WebSocket as I'm self hosting...or haven't figured out how to make that work. Whenever I connect using web sockets from the client console program and my server calls a client function, the client spirals into a connect/disconnect loop.

Now, if I add a System.Threading.Thread.Sleep(1) after I send the object in my loop while using LongPollingTransport, I don't seem to lose any transactions on the client side. Is there a bug on the sending side or am I supposed to always manage how fast I'm calling client methods? 

Note, if I use ServerSentEventsTransport it still loses messages even with a sleep.. It seems like I have to slow down sending?

**Comment by jiangyh1024** [comment]
@mkuzminski  sorry to bother, I have the same situation as yours. I need to send message to client in a for loop. But it is too fast, some messages are missing. How did you solve it?

**Comment by firephantomassasin** [comment]
@mkuzminski @jiangyh1024  hi guys, i am experiencing the same issue. how did you solve it?

**Comment by igorgontar** [comment]
I think it's a fundamental design flaw. The problem they try to address here is commonly known as "slow consumer detection and handling" in pub/sub systems. One of the simplest strategy to implement is to start dropping messages, if slow consumer can not catch up with the speed of the fast producer.
The problem with signalR is that they reuse MessageStore implementation backed by ring buffer everywhere, including places, where it does not make sense at all. This ring buffer approach with message dropping strategy makes sense, when there are multiple consumers/readers of the stream, like on a Topic.  
If you simply stream messages from the server to an individual client, signalR internally creates a channel using the same ring buffer backed store, while in this case the most suitable implementation would be simply a blocking queue.
This affects long-polling hardly. You don't need to be super aggressive. Just setup the buffer size=50 (32 is the absolute minimum allowed) and try to push 100 messages to the client in the loop. You will see the message drops immediately. For long-polling it would be nice if server can block for a reasonable (configurable) amount of time if the buffer is full, giving a client the chance to come back with the next polling request and read the rest of messages.   
 
Another problem is that you can't configure that message buffer size per client or Hub, etc. It's a global setting, which forces you to make difficult decision: message drops or memory issues.

It's very poor, minimalistic implementation. It could be implemented a bit more intelligently. Like... 
start with a small buffer, let it grow until some configurable limit, if does not help try slowing down the producer by blocking it for some configurable amount of time, if does not help, start dropping messages Potentially, disconnect slow consumer if the rate of message drops is too high. 
Would be also nice to make this strategy parameters configurable per client, topic, Hub, etc. , because certain scenarios are absolutely fine for one application and are not acceptable for the other.

Yet another problem is that message buffer size is effectively the number of messages and has not relation to the actual message size.
So, I see big potential of misusing the whole concept to solve the issue with message drops by accumulating messages on application level and then posting them as one big message.... would be too bad.

Hope .net Core version of SignalR will address this problem differently.

**Comment by davidfowl** [comment]
> Hope .net Core version of SignalR will address this problem differently.

It does.
