### ISSUE TITLE
Singalr 2.0 .net client times out when trying to connect (with repro)

### ISSUE THREAD

**Issue by jalchr** [SignalR/SignalR#2669]
Sorry if this issue looks trivial, I really searched as much as I could for a proper exit, but with no success.
Here is some of the stack trace:

10:36:48.3002224 - 30e604ef-6db6-4967-b75b-2af7afae1055 - LP Connect: http://localhost:2178/signalr/connect
10:36:48.3652269 - 30e604ef-6db6-4967-b75b-2af7afae1055 - Auto: Failed to connect to using transport longPolling. System.TimeoutException: Transport timed out trying to connect
Connecting => Disconnected
10:36:48.3682261 - 30e604ef-6db6-4967-b75b-2af7afae1055 - Disconnected
10:36:48.3702251 - 30e604ef-6db6-4967-b75b-2af7afae1055 - Transport.Dispose(30e6
04ef-6db6-4967-b75b-2af7afae1055)
10:36:48.3712271 - 30e604ef-6db6-4967-b75b-2af7afae1055 - Closed
10:36:48.5022325 - null - Error: System.TimeoutException: Transport timed out trying to connect

Repro: https://dl.dropboxusercontent.com/u/42372199/Signalr2.zip

**Comment by amialeo** [comment]
Old thread but stumbled on this since I had the same issue.
My issue was "A first chance exception of type 'System.MissingMethodException' occurred in Microsoft.AspNet.SignalR.Client.dll"

SignalR version 2.0.1 but JSON.NET (newtonsoft.json) version is 4.5
The issue was resolved when I removed the newtownsoft.json.dll and downloaded the latest JSON.NET through NuGet (v 6.0).
