### ISSUE TITLE
Task for Groups.Add never completes

### ISSUE THREAD

**Issue by bp74** [SignalR/SignalR#3037]
Let's start with a simple code snippet:

```
var groupName = string.Format("channel/{0}/{1}", channelNumber, language);
var hubContext = GlobalHost.ConnectionManager.GetHubContext<LiveFeedHub>();
await hubContext.Groups.Add(connectionID, groupName);
await hubContext.Clients.Client(connectionID).init(initPackage);
```

So i want to add a connectionID to a group and then send a message to the client.

The problem is that the await for the first Task never completes. If i remove the await, the connectionID is added to the group successfully! I know it because the client receives broadcast messages for this group afterwards. The await for the second Task works perfectly fine.

This is my setup: 
- The system works with SignalR Scaleout 2.0.3. 
- The Scaleout backplane is using Service Bus for Windows 1.1.
- The code runs in a Windows Services on the backend.
- The clients connect to the hub via a website running on IIS.

Btw. The same is true for hubContext.Groups.Remove(..). If you await the completion of the remove operation, you have to wait forever.

Thanks a lot for your help!

**Comment by bp74** [comment]
I did a quick test with the new 2.2 version and the Groups.Add method task finishes successfully. Unfortunately the same bug still occures with the Groups.Remove task. This Tasks completes with a timeout after some time.

**Comment by kbirger** [comment]
For what it's worth, I still occasionally see Groups.Add timing out. I can't isolate when it happens, and I'm not using scaleout. It's worth noting that if I add a ContinueWith to groups.add which fires on the taskcanceled case and I do Clients.Group(thatGroup).InvokeSomething(), the message is received. So it seems that while the Ack didn't make it in time, the client DID receive the group registration?

**Comment by stricq** [comment]
I am also seeing Groups.Add timeout when not using any scaleout.

**Comment by halter73** [comment]
@stricq Can you give us some more details?

It's not entirely unexpected that Groups.Add will timeout infrequently. This can happen if the client you are adding to the group has disconnected from the server, because Groups.Add waits on an ACK.

If the timeouts are happening frequently, it would be very helpful if you could provide some sort of sample app the repros this. Thanks.

**Comment by niemyjski** [comment]
@halter73 here is a sample app that reproduces this: https://github.com/exceptionless/Exceptionless

**Comment by ArturPhilibin** [comment]
Hi @halter73 I'm working on a project that seems to run into this issue pretty consistently although not 100% of the time. Occasionally after a nightly build and deploy everything works fine, but most of the time we run into the constant TaskCanceledException due to timeout issue. Our setup is similar to others, especially [Issue 3042](https://github.com/SignalR/SignalR/issues/3042). 
2 SignalR instances
Redis backplane
Clients connecting with Server Sent Events

I noticed people mentioning that upgrading to 2.2.2 seems to have resolved the issue for them, but it's not the case for us, i fails just as regularly (most of the time) as did version 2.2.0. I also noticed the [commit intended to fix this issue](https://github.com/SignalR/SignalR/commit/5f110f4a88fc5665acd6eb46cbb8f605cae22b78) was almost rolled back for [another solution](https://github.com/SignalR/SignalR/commit/e7ce0b07f9539a1e5a9f39af2f3d35de359f9a5e?diff=unified).

Is this issue still being investigated? I cant give a sample application that reproduces the issue, but I noticed @niemyjski  has

**Comment by halter73** [comment]
> constant TaskCanceledException

@ArturPhilibin If you are getting TaskCanceledExceptions consistently on 2.2.2, I suspect there might be an issue with your Redis backplane configuration. Can you confirm that if you broadcast a message from a one SignalR instance, clients connected to the other instance still get the message?

Like I mentioned before, TaskCanceledException are expected when using a backplane when a client disconnects as it's being added to a group, but it shouldn't be a consistent issue.

Assuming the backplane is configured correctly, I would need to see where and how Groups.Add is called to determine why it could fail. I don't think Exceptionless counts as a repro considering it doesn't use SignalR atm.

**Comment by ArturPhilibin** [comment]
Hi @halter73 it turn out to be a red herring, our situation looked so similar to the above mentioned issues that we thought it was the same, but it turned out to be [a connection sharing client](https://github.com/slimjack/IWC/) we use that is causing the issue
