### ISSUE TITLE
ASP.NET Hub.OnDisconnected not called when .NET client disconnects due to Internet connectivity/process killed

### ISSUE THREAD

**Issue by jbrx107** [SignalR/SignalR#3115]
Repro steps:
- Add this method to the Hub on the ASP.NET side:

public override Task OnDisconnected()
- Deploy the server app into an Azure Website
- Create a .NET (C#) client and connect to the now-deployed ASP.NET app
- Verify that OnConnected is called on the Hub on ASP.NET - so far so good
- Now, kill the C# client process using task manager/stop in the VS debugger/etc.
- OnDisconnected on the ASP.NET server side is _never_ called even after waiting hours.
- This is with the latest stable version of SignalR.  This causes significant issues in my app.

Questions:
- Is this a known issue?  It's a pretty serious problem
- Are there any workarounds?

**Comment by ppumkin** [comment]
I struggled a few hours with this. I am using SignalR 2

On a basic script you need to define at least one client callback for events to be raised on the hub..... I eventually found this while [running an example from here.][1]


    chat = $.connection.chatHub;

    // Need at least one callback for events to be raised on the hub
    chat.client.void = function () { };

    $.connection.hub.logging = true;
    $.connection.hub.start(); //.done(function () {

Now, after all that digging, my breakpoints **finally** get hit on the OWIN C# server.


    public override Task OnConnected()
    {
       //logic code removed for brevity
       return base.OnConnected();
    }

    public override Task OnDisconnected(bool stopCalled)
    { 
       //logic code removed for brevity
       return base.OnDisconnected(stopCalled);
    }


  [1]: https://github.com/DamianEdwards/NDCLondon2013/tree/master/UserPresence

**Comment by blindberg74** [comment]
Hello All,
I am using SignalR 2.2.1 and I'm seeing this issue using a javascript client in a chrome browser. After turning on the signalr logging I do see the connection being aborted because of a timeout but the OnDisconnected event is never called on the hub. Is this still an issue. I have also tried using the javascript onbeforeunload to manually call disconnect on the hub but this did not work.

`        public override Task OnDisconnected(bool stopCalled)
        {
            try
            {
                using (LogContext.PushProperty("ClientConnectionId", Context.ConnectionId))
                {
                    using (LogContext.PushProperty("StopCalled", stopCalled))
                    {
                        Log.Warning(stopCalled
                                ? "Client {ConnectionId} explicitly closed the connection."
                                : "Client {ConnectionId} timed out.", Context.ConnectionId);

                        return base.OnDisconnected(stopCalled);
                    }
                }
            }
            catch (Exception exception)
            {
                Log.Error(exception, "Error OnDisconnected");

                throw new HubException(exception.Message);
            }
        }`

SignalR Logs:
SignalR.Transports.TransportHeartBeat Information: 0 : Connection 71162383-1336-457c-92a5-3e7ed55c9f8f is New.
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.ServerSentEventsTransport Information: 0 : Abort(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.TransportHeartBeat Information: 0 : Removing connection 71162383-1336-457c-92a5-3e7ed55c9f8f
SignalR.Transports.ServerSentEventsTransport Information: 0 : End(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.ServerSentEventsTransport Verbose: 0 : DrainWrites(71162383-1336-457c-92a5-3e7ed55c9f8f)
SignalR.Transports.ServerSentEventsTransport Information: 0 : CompleteRequest (71162383-1336-457c-92a5-3e7ed55c9f8f)

**Comment by halter73** [comment]
@blindberg74 Are you sure that `OnConnected` was called on the same hub for the same client before disconnecting?

**Comment by halter73** [comment]
@blindberg74 Are you sure that `OnConnected` was called on the same hub for the same client before disconnecting?

**Comment by blindberg74** [comment]
Yes I have verified that the initial connection was made.

**Comment by battermaster** [comment]
Yes, I met the problem too.

**Comment by gsferreira** [comment]
There's any recommendation to deal with the cases when the OnDisconnected is invoked without calling the Stop on the Client? I want to try to inform my client that he's no longer recognized by the Server.

**Comment by fabercs** [comment]
@blindberg74 @halter73 Is there any progress on this? I am using SignalR 2.2.2 and having the same issue. My .Net client connects and server OnConnected fires properly, however when connection.Stop() on client, OnDisconnected() is never hit.

**Comment by mkorganashvili** [comment]
Is there any news?

**Comment by anurse** [comment]
This issue was closed a while ago, please file a new issue with a description of the expected behavior and the actual behavior. If possible, please collect client and server traces as described in the [SignalR Tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing) documentation and attach them to the issue.
