### ISSUE TITLE
DefaultDepenencyResolver is leaking hubs 

### ISSUE THREAD

**Issue by SofianHn** [SignalR/SignalR#3208]
The number of hubs in memory is increasing under load. After inspecting the memory I am seeing the hubs are kept alive by the DefaultDependencyResolver specifically by a HashSet<IDisposable> (I am guessing it's _trackedDisposables). 

The size of this hash set is increasing as well, it's ending up in the LOH eventually. The hubs are registered as suggested in http://www.asp.net/signalr/overview/signalr-20/extensibility/dependency-injection: 
GlobalHost.DependencyResolver.Register(typeof(MyHub), () => new MyHub(somevar));

**Comment by andyste1** [comment]
I'm seeing this memory issue in v2.2. I'm using a Castle Windsor-based hub activator - am I missing something or doesn't the above fix (Sep 23, 2014) address this particular scenario? For info here is my activator class:-

    internal class WindsorHubActivator : IHubActivator
    {
        private readonly IWindsorContainer _container;

        public WindsorHubActivator(IWindsorContainer container)
        {
            _container = container;
        }

        public IHub Create(HubDescriptor descriptor)
        {
            var hubType = descriptor.HubType;
            return _container.Resolve(hubType) as IHub;
        }
    }

**Comment by IanYates** [comment]
This isn't the cause of your problem.

There's another issue with SignalR and Windsor.  See #2908 and also follow the link at the end to #3387 so you don't ruin hub group registrations, etc.

Windsor strictly follows the "release what you resolve" paradigm.  That's great, but there's no elegant hook in SignalR to do the release part.  SignalR calls Dispose() on hubs, but not in a way that you can intercept.  

I used to use singleton registrations for my hubs but that lead to issues with SignalR group management because SignalR injects (via properties) things like Context, Group, etc into the hub object after it's constructed.  So you really can't share Hub instances as singletons.

But you don't want Windsor to track them forever...  So register them as transient, then release immediately upon calling resolve (with some appropriate 'here be dragons' comment to explain the unorthodox approach).  So long as your Hub disposal actually does nothing (as mine happen to do) you get Windsor not tracking your Hubs, SignalR getting discrete Hub instances and all the DI goodness that Windsor provides :)
