### ISSUE TITLE
Server to client message ordering NOT preserved

### ISSUE THREAD

**Issue by davhdavh** [SignalR/SignalR#3310]
Microsoft.AspNet.SignalR.SqlServer does not preserve ordering of messages sent from server to client...

``` csharp
   public class MyHub1 : Hub
   {
      public void Hello()
      {
         var connId = Context.ConnectionId;
         var context = GlobalHost.ConnectionManager.GetHubContext<MyHub1>();
         for (int i = 0; i < 5; i++)
         {
            context.Clients.Client(connId).Hest(i);
         }
      }
   }
```

Will always return 0,1,2,3,4 in NON-SQL-scaleout scenarios, but will often return out of order when using GlobalHost.DependencyResolver.UseSqlServer(new SqlScaleoutConfiguration("..."))

Using SSE or websockets makes no difference.
Using 1 or 10 webservers makes no difference.
Using sql server 2005 or sql server 2014 makes no difference.

**Comment by nadavtenne** [comment]
any solution ? its 2018

**Comment by nightmare233** [comment]
##-Please type your reply above this line-##
 
 Hi {!Ticket.Name} , 
  
 Thank you for contacting us! 
  
 We have received your query as below: 
  
 any solution ? its 2018

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/SignalR/SignalR/issues/3310#issuecomment-364764182 
  
 To help track your query, we have generated a Comm100 Ticket Id. Your Comm100 ticket Id is S34008-T124. Please include this ticket number in all your communications with us. 
  
 We will resolve your query and contact you as soon as possible. 
  
 If you have any other question, please feel free to contact us. 
  
 Sincerely yours, 
  
 



CNaqH_OgpPM_harDr

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
