### ISSUE TITLE
Connection stuck while having network outages, leading to memory leak and and application freeze

### ISSUE THREAD

**Issue by ayarov** [SignalR/SignalR#3353]
I'm working with a .Net client 2.1.2
We lately upgraded it from the old 1.xxx version

Now, we are trying to simulate unstable environment were from time to time connection issues.
To be more specific, i simulated a WI-FI disabling and enabling after a while.
It leaded me to communication channel stuck: no message could be sent, no receive, not even Stop connection.
By looking deeper i found that at some point there were hundreds of threads up in the air due to  bad implementation of the Heartbeat callback event.
Also, the CheckKeepAlive method has a lock on its enterence, it means that all of this threads are stuck until the first one that is trying to abort will not complete (in that case i have my doubt whether the abort is going to end at some point). So in the meanwhile the heartbeat is ticking and generating more and more threads hanging the application.
![image](https://cloud.githubusercontent.com/assets/3107006/5254268/b2cfaa70-79b7-11e4-9668-fa49d711145b.png)

**Comment by sisterray** [comment]
Any news on this. I am using SignalR Client v2.2.0 in a Xamarin app and I am getting exactly the same error. Will this be fixed in v2.2.1? If so is there any news on when this will be, it was thought this would be available after December 2015 but there is still no sign of it. This is a major issue for me as I cannot reestablish my connection due to the locking problem

If there is no fix, is there a workaround you could suggest

**Comment by raghav-khunger** [comment]
Hi,

We are facing a similar issue like this. 

When we start our application, after a while all the users connected to the hub start getting reconnecting issues.

In Chrome console all the users are seeing this continuously:

> jquery.signalR.min.js WebSocket connection to 'wss://[our site url]/signalr/reconnect?transport=webSocke…HcDfA%3D%3D&connectionData=%5B%7B%22name%22%3A%22myhub%22%7D%5D&tid=10' failed: Error during WebSocket handshake: Unexpected response code: 404

All the users are stuck in reconnecting mode i.e this method is continuously firing for all users:

```
connection.hub.stateChanged(function (change) {
                if (change.newState === $.connection.connectionState.reconnecting) {
                    failPendingMessages();
                    ui.showStatus(1, '');
                }
                else if (change.newState === $.connection.connectionState.connected) {
                    if (!initial) {
                        ui.showStatus(0, $.connection.hub.transport.name);
                        ui.setReadOnly(false);
                    } else {
                        ui.initializeConnectionStatus($.connection.hub.transport.name);
                    }

                    initial = false;
                }
                else if (change.newState === $.connection.connectionState.disconnected && initial === true) {
                    initial = false;
                }
            });

```
We are using that code from the Jabbr source code.

The state is changing from connected > reconnecting > diconnected> connected

Seems after a while when there are many connections, all the connections to Hub remain stuck i.e are not able to converse with hub properly and hence connection gets broken and we receive "WebSocket handshake: Unexpected response code: 404" what I mentioned above.

Note that there is not a fixed time for this behavior/issue. Sometimes it starts with in few minutes of "application start" and sometimes it takes around 20-30 minutes. 

This issue definitely seems to be because of many connections conversing at the same time to the Signalr core code via Hub.

Is there any fix for it?

**Comment by sisterray** [comment]
Any word on a fix for this? I can make this happen easily in a Xamarin app. Unfortunately all the PCL profiles only use .NET 4.5 so there is no chance of moving to a later version of the .NET framework. This is a really big issue for me. Can it be fixed or can a workaround be provided

**Comment by davidfowl** [comment]
@sisterray Did you file a bug on Xamarin?

**Comment by TingtingAn** [comment]
@sisterray   any solution for the issue? I am hitting it.

**Comment by sisterray** [comment]
This is a comment I place on #645 which seemed to fix the issue for me

You could try a couple of things

Upgrade to 2.2.1
Ensure that you cleanly manage the connection, e.g. Ensure the the previous connection is cleanly disposed of before setting your connection to a new one.
Don't abort or dispose of a connection that failed to connect, e.g. One with no connection Id. I found this seemed to work on iOS but crashed on Android. I suspect it didn't really work on iOS but eventually causes the locking issue.
Since I have done this the issue has gone.

**Comment by nirajkr** [comment]
@sisterray  is this issue fixed ? I am using 2.2.3 and still facing the same issue

**Comment by sisterray** [comment]
There was no fix, I am using 2.2.1

Just follow the points I made in my previous comment. If that doesn't fix it it is probably another issue

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by anurse** [comment]
It looks like there's still some activity on this thread. @nirajkr or @sisterray could one of you open a new bug and describe what you're seeing? There's a lot going on in this thread (including some slightly different but possibly related issues) so it's difficult to track down exactly which issue you're seeing :).

**Comment by patsadow2** [comment]
2.4.0 Still the same issue long hubConnection.Stop(); of application in Xamarin.Froms ;/
