### ISSUE TITLE
SignalR Message buffer 

### ISSUE THREAD

**Issue by JigneshChovatia** [SignalR/SignalR#3369]
We have a signalr server hosted on window service, the service memory is increasing day to day ,I have checked in memory profiler and found signalr Message class consuming memory.

As per my knowledge signalr is buffering messages on server.

I some have a question regarding buffering.

After how much time signalr will release buffer once client is disconnected ?

Can we manage to release memory from window service when the users are logged off?

Thanks

**Comment by kohner86** [comment]
I've been having the same issue for quite some time.  Last time I brought this up the response was that it wasn't a bug per say but that it was some sort of buffer which would grow unbounded and would never shrink in size.  My only solution has been to just let the IIS App pool recycle since AFAIK there doesn't seem to be a plan to fix the issue.

**Comment by halter73** [comment]
If you are experiencing *unbounded* growth in SignalR's memory consumption, that is definitely a bug. We take memory leaks very seriously.

However, keep in mind, SignalR's [message buffers](https://github.com/SignalR/SignalR/blob/2.1.2/src/Microsoft.AspNet.SignalR.Core/Messaging/MessageStore.cs) are bounded. SignalR message buffers are [ring buffers](http://en.wikipedia.org/wiki/Circular_buffer).

As @erickallemeyn mentioned, you can configure the maximum number of messages each ring buffer will store using `GlobalHost.Configuration.DefaultMessageBufferSize`. If you try to set this value to less than 32, SignalR will set the ring buffer capacity to its minimum value of 32.

**Comment by kohner86** [comment]
Sorry if the previous comment was a bit harsh, we've had this issue come and go seemingly randomly for quite some time...

The issue I've been experiencing seems to pop up whenever the BookSleave connection used for the backplane drops the connection (we're using Azure's managed redis).  What then happens (maybe 5% of the time) is that the web server CPU/RAM slowly rise until the memory limit is hit.

I've run a profiler on the server and the hot path always comes back as:

87% System.Threading.ThreadPoolWorkQueue.Dispatch
Execution on lines: 0
86% System.Threading.Tasks.Task.ExecuteEntry
86% System.Threading.Tasks.Task.ExecuteWithThreadLocal
86% System.Threading.ExecutionContext.Run
86% System.Threading.ExecutionContext.RunInternal
86% System.Threading.Tasks.Task.Execute
86% Microsoft.AspNet.SignalR.TaskAsyncHelper+<>.<ContinueWithPreservedCulture>b__27
86% Microsoft.AspNet.SignalR.TaskAsyncHelper+TaskRunners`2+<><RunTask>b__33
86% Microsoft.AspNet.SignalR.Redis.RedisMessageBus+<><SendImpl>b__1
45% Microsoft.AspNet.SignalR.Redis.RedisMessageBus.ExecuteTransaction
45% BookSleeve.RedisTransaction.Execute
45% BookSleeve.RedisConnectionBase.EnqueueMessage


We only have around 100 or so active connections at any given moment and from the server monitoring we use (New Relic) their doesn't seem to be any correlation between the SignalR traffic and the CPU/RAM consumption so it doesn't seem like something caused by all of the clients trying to reconnect at once.

**Comment by halter73** [comment]
No worries. The description you give definitely makes it seem like you are running into a bug with our Redis implementation.

In SignalR 2.2.0, which we plan to release next week, we have rewritten our Redis package to use [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis) instead of BookSleeve.

You can try out the package right now from our nightly feed: https://www.myget.org/gallery/aspnetwebstacknightly

If you still experience this issue (I understand that this might not be hard to repro if it happens 5% of the time), it would be great if you could file a new issue.

**Comment by JigneshChovatia** [comment]
My signlar server is hosted under windowsservice, is there anything to do from my side to clear ring buffer as per my R&D, seems server is not clearing memory after disconnecting client.

**Comment by JigneshChovatia** [comment]
one more thing my message is 4-8kb .

**Comment by erickallemeyn** [comment]
Have you run a memory profile with something like ANTS or Dynatrace? 

As per my closed issue at: https://github.com/SignalR/SignalR/issues/3291 , the memory usage in the windows task manager is a bit misleading. Windows will manage the memory in such a way that it may *appear* to be using a large amount of memory, but the OS will release it to other requesting programs when it is running up to the limit. If your memory profile looks like the one above, I would not worry about it.

**Comment by JigneshChovatia** [comment]
Yes, I have run memory profiler in dump from production server. when I have take dump at that time 
task manager displaying 250 mb allocation.
I have only 65-70 clients connected to server and server was started before 5 days from dump taken.
![memoryprofiler](https://cloud.githubusercontent.com/assets/10304695/5716950/25b97b56-9b1e-11e4-9cf8-3adbbcc8d8aa.png)

**Comment by DamianEdwards** [comment]
I'd encourage you to try the latest version of our Redis backplane as we removed the use of Redis transactions (as indicated in your profile posted earlier) a few versions back.

Also, your memory profile doesn't show anything odd, assuming your messaging pattern is that you send messages to individual users/connections. A couple hundred MB of active memory use for that many clients after that many days is perfectly normal. If you want to reduce it you can adjust the message buffer size as others have pointed out.

**Comment by JigneshChovatia** [comment]
Thanks damian for your reply. 
yes I am sending message to individual client.
Still everyday memory is increasing about 8-10 mb per day, will it be static at some level? 
My clients are connected 24X7 and buffer should be full now and My buffer size is 500.

**Comment by xyzish** [comment]
> My signlar server is hosted under windowsservice, is there anything to do from my side to clear ring buffer. as per my R&D, seems server is not clearing memory after disconnecting client. Is signalr buffering the message if it is delivered to client? One more thing my message is 4-8kb do I need to reduce message size?.

How about this question, Is signalr buffering the message if it is delivered to client and when the buffer memory exceed the DefaultMessageBufferSize, and the server will lose messages for sure, but after a few seconds the client reconnects and consumes the messages in buffer memory, does it reduce the size?

**Comment by halter73** [comment]
> but after a few seconds the client reconnects and consumes the messages in buffer memory, does it reduce the size?

I normally don't recommend asking questions like this on issues that haven't had any activity in over 7 years, the answer is no. SignalR isn't buffering for individual clients but for all clients that might be a recipient of the message and might reconnect. SignalR also doesn't ACK messages, so it has no way to know if the message has really been consumed by the client.
