### ISSUE TITLE
Task for Groups.Remove never completes

### ISSUE THREAD

**Issue by bp74** [SignalR/SignalR#3382]
Please revisit issue  #3037

This issue was closed because it was fixed for the 2.2 release of SignalR. Unfortunately only the issue with Groups.Add was fixed, but Groups.Remove still blocks and only completes after a timeout.

**Comment by halter73** [comment]
Thanks for the report. I just manually retested `Groups.Remove` in the three known scenarios it would previously fail/timeout. These scenarios are:

1. When removing a client other than the caller from a group in a Hub method or `PersistentConnection.OnReceived` and the client being removed is on another server.

2. When removing any client including the caller from a group in a Hub method or `PersistentConnection.OnReceived` when the /connect request of the client triggering the removal is being processed by a server other than the one where `Groups.Remove` is called.

3. When calling `Groups.Remove` on an `IHubContext` or `IPersistentConnectionContext` provided by the `ConnectionManager` to remove a client connected to another server.

In all three cases, I see the call to Groups.Remove completing very quickly.

If you try to remove a client from a group that is no longer connected to any SignalR server, it is expected that `Groups.Remove` will fail with a canceled task after 30 second. This is basically because the client being removed from a group will never be able to acknowledge that it has received the command. Perhaps this is the issue you are running into?

If you are sure the client you are trying to remove from a group is still connected, I think we are going to need more details about how to reproduce your scenario so we can fix this issue.

**Comment by bp74** [comment]
Thank you very much for your extensive testing in this case. Yes you are probably right that i called the Groups.Remove method with a connection that is already disconnected. In fact i didn't know that there is an ACK from the client. 

So if a client is disconnected already calling Groups.Remove wouldn't make much sense anyway because the connection is removed from the Group anyway, right?

Again, thank you very much for looking into this!

**Comment by halter73** [comment]
If you know a client has disconnected, I see no reason to try to remove it from a group. SignalR will handle cleaning up any internal state related to a disconnected client.

There might not be a need for you to ever await a call to `Groups.Remove`. The main reason for awaiting `Groups.Add` is to ensure that subsequent messages sent to the group will be received by the newly added client. Often the inverse isn't as important.

I should add that it is not possible to securely remove a client from a group. Each SignalR client is  responsible for holding onto an encrypted token containing a list of all the groups the client is currently a member of. This is the `groupsToken` you can see in the query string of SignalR reconnect requests.

This also means that while a malicious client cannot join a group is was never a member of (because the `groupsToken` is encrypted preventing manipulation of the list of groups), a malicious client could use an old `groupsToken` to rejoin a group it was removed from. This is not an issue for well-behaving clients that will use the most recently received `groupsToken` when reconnecting.

**Comment by lvvdat** [comment]
I also have a similar issue.
I removed a client connection (Group.Remove) from a group and the job was completed, but this client still receive the messages from this group.
How can I really remove this customer out of the group and cannot receive any messages from this group.

Thanks
