### ISSUE TITLE
SignalR - Always uses 3 connections between Client and Server.

### ISSUE THREAD

**Issue by simonpbond** [SignalR/SignalR#3384]
When establishing a SignalR (websocket) connection, I get 3 separate TCP Connections showing in Resource Monitor.

I also used Performance Counters and noticed 3 "Web Service\Current Connections" for every 1 "SignalR\Current Connection".

Why is there a 3:1 ratio of TCP Connections to single SignalR (WebSocket) Connections.

Is this expected behaviour?

**Comment by simonpbond** [comment]
The 2 additional connections eventually close after some time.

Is it normal for SignalR to open 3 TCP connections on initial negotiation? Then drop 2 of them?

Is this expected behaviour?

When load testing a SignalR server for 50,000 concurrent clients our server now needs to handle 150,000 initial connections. Painful !

**Comment by moozzyk** [comment]
The SignalR client sends 3 requests when starting a connection - negotiate, connect and start. negotiate and start are HTTP requests and are short lived. The `connect` request cause switching protocols for websockets and open a long lived connection. How OS handles TCP connections for HTTP requests is orthogonal to SignalR since SignalR is directly using only HTTP stack and therefore does not have access to the TCP layer.

**Comment by dzubrilin** [comment]
The next question then - is there a way of controlling 'Keep-Alive' header for negotiate and start messages in HTTP requests (something similar to https://msdn.microsoft.com/en-us/library/aa345277.aspx)?
