### ISSUE TITLE
Cannot install portable NET client package

### ISSUE THREAD

**Issue by Unrefraction** [SignalR/SignalR#3393]
Hi everyone, 

I was trying to update SignalR client package from 2.1.2 to 2.2, but I got this:
`Install-Package : Could not install package 'Microsoft.AspNet.SignalR.Client 2.2.0'. You are trying to install this package into a project that targets 'portable-net45+sl50+win+wpa81+wp80', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.`

I assume, PCL compatibility is broken.

**Comment by governor281** [comment]
What .NET framework is your project targeting? I received a similar error and it was because i was targeting .NET 4.0 and needed .NET 4.5

**Comment by Unrefraction** [comment]
@governor281, it's targeting NET45 (and also Win8, WP 8.1, Silverlight 5, WP Silverlight 8).

**Comment by moozzyk** [comment]
@governor281 - can you provide repro steps? I just created a blank C# console app, installed 2.1.2 SignalR client NuGet package and updated to 2.2.0 SignalR client NuGet package without any errors.

**Comment by jeffijoe** [comment]
I've got the same problem - I can install 2.1.2, but not install 2.2.0, nor upgrade from 2.1.2 to 2.2.0.

**Comment by governor281** [comment]
@moozzyk  i was just trying to help ...@Unrefraction is the one with the issue

**Comment by moozzyk** [comment]
@governor281 - yeah, sorry

@jeffijoe , @Unrefraction - please provide more details, steps, or show a sample project.

**Comment by Unrefraction** [comment]
@moozzyk 
1) Create new project NET45 - Class Library (Portable);
2) Select the next targets: NET45, Win8, WP 8.1, Silverlight 5, WP Silverlight 8 (all selected by default);
3) After new project is created, try to install SignalR NET client package 2.2.0
or
3) Install SignalR NET client 2.1.2;
4) Try to update to 2.2.0.

**Comment by moozzyk** [comment]
@Unrefraction - thanks for the details. I think this is because in 2.2.0 we have a separate package for WP81 which contains websocket transport. I will look into it.

**Comment by sisterray** [comment]
Hi,

Is there a solution available for this problem, or a workaround available

Thanks

**Comment by moozzyk** [comment]
The problem here is that it if the project targets net45 and wpa81 we don't have a subset that satisfies this condition - we only have:
portable-net45+sl5+netcore45+wp8+wp81
portable-win81+wpa81

To fix this we may need to ship store transport in a separate package which will be pulled in as a dependency of the Microsoft.AspNet.SignalR.Client package if the project targets wpa81. 

A (not beautiful) work around for now is to extract binaries from the package and add references manually.

**Comment by moozzyk** [comment]
Actually, if you are targeting both net45 and wpa81 you should not never get the store websocket transport. This is because it is not websockets transport can run only on wpa81 so making it available in net45+wpa81 configuration would cause problem. The fix then would be to change `net45+sl5+netcore45+wp8+wp81` the subset to contain `win81+wpa81` so that you will just get the client .dll and not websocket transport in this configuraion. 

As a result the workaround seems to be to uncheck Windows Phone 8.1. if you target net45 to get just Microsoft.AspNet.SignalR.Client.dll but not the Websocket dll.

**Comment by moozzyk** [comment]
Fixed in 9951d04631e092bdad2287615dcfbff14619396c

**Comment by tofutim** [comment]
moozzyk, will there be a 2.2.1 release in nuget?

**Comment by moozzyk** [comment]
Yes. We need to finish build verification.

**Comment by tofutim** [comment]
Will it
support portable-net45+win8+wpa81+MonoAndroid10+Xamarin.iOS10+MonoTouch10+Xamarin.Mac20

**Comment by tofutim** [comment]
I tried 2.2.1-pre-160120-b693 from the nightlies, and am able to add the
nuget package.

**Comment by moozzyk** [comment]
:+1:

**Comment by tofutim** [comment]
What is the ETA on 2.2.1 official?

**Comment by nlcoolcool** [comment]
i have the same problem. how can i get the fix? i dont see 2.2.1 prelease in NuGet Package Manager.

**Comment by tofutim** [comment]
@nicoolcool You have to use the ASP.NET nightlies.

https://www.myget.org/F/aspnetwebstacknightly/
