### ISSUE TITLE
StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by imperugo** [SignalR/SignalR#3405]
Why StackExchange.Redis.StrongName instead of StackExchange.Redis?

Most applications use StackExchange.Redis, adding SignalR means have two packages for the same thing.
Isn't it?

**Comment by moozzyk** [comment]
A strong named assembly can only reference assemblies signed with strong name. Since SignalR assemblies are strong named they cannot reference StackExchange.Redis. Note that non-strong named assemblies can reference strong named assemblies so you can use StackExchange.Redis.StrongName in your project and therefore have just one package.

**Comment by imperugo** [comment]
I didn't notice that SignalR assembly was signed.
Really I don't understand why today someone is still using signed assembly, but your point makes sense.

Thanks
.u
