### ISSUE TITLE
Changing transport protocol in case of DNS error through websockets

### ISSUE THREAD

**Issue by DennisFrostlander** [SignalR/SignalR#3450]
Hi,

We have encountered a few very similar cases when our users had DNS problems with websockets. Namely, connecting to a /reconnect endpoint using ws://domain.com results in a standard error ERR_NAME_NOT_RESOLVED. Interestingly enough, the 'normal' HTTP requests to exactly the same domain work just fine.
We were not able to really find the root cause of this issue, but there is one thing in common in all cases - changing network (some people were changing office buildings, other people changed internet provider, etc).

But anyway, the issue with signalr in this case is that it does not automatically change the transport to something else if the websocket request to /reconnect endpoint fails with such error.
If I just catch the error in connection.start().fail() and then specifically provide a different mode of transport, then everything works fine.
It would be nice if signalr did this out of the box. Thanks.

**Comment by moozzyk** [comment]
Reconnect is not connect. Reconnect is just resuming a broken connection. The client does not really know what went wrong and just keeps trying reconnecting for a configured amount of time using settings negotiated when the connection was started. If it cannot reconnect within the timeout it will just give up. To be able to change the transport SignalR client would have to stop the existing connection and start a new one since the server is expecting the requests on the transport the client originally used to connect. At this point this is no longer a reconnect and can as well be handled on the user side with the current bits.
