### ISSUE TITLE
SignalR 2.2, IIS 8.5(Server 2012r2) WebSockets connection fails (contemplating suicide)

### ISSUE THREAD

**Issue by LastTribunal** [SignalR/SignalR#3482]
For the life of me, I can't get neither my .Net or the Web client to connect to my IIS hub over WebSockets.  Works with LongPolling (but this is a crap protocol)

Tried every f'n trick in the book... Anyone confirm that it works in their in their environment?
If so, let me know...

19:12:50.5568557 - null - ChangeState(Disconnected, Connecting)
19:12:50.6038557 - 244717bb-7161-4575-b770-46a421e7f961 - WS Connecting to: ws://localhost/hub/signalr/signalr/connect?clientProtocol=1.4&transport=webSockets&connectionData=[{"Name":"MainHub"}]&connectionToken=vqwRxfdBXKlrfqi7VcED%2FQKLvadAJx8v%2BJCUQJDaI9UzQmJGZxEZzs0JgxjBqf7lmmStDmqBSYCDZAnBSHNwHCG%2FMEAJwySkb9h2eY71pagUE7AWCCAZLp%2B1LMiAKM%2F6
19:12:50.6118557 - 244717bb-7161-4575-b770-46a421e7f961 - Disconnected
19:12:50.6118557 - 244717bb-7161-4575-b770-46a421e7f961 - Transport.Dispose(244717bb-7161-4575-b770-46a421e7f961)
19:12:50.6118557 - 244717bb-7161-4575-b770-46a421e7f961 - Closed
19:13:10.4178557 - null - Error: System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.

**Comment by gbaquedano** [comment]
Did you enable WebSocket protocol at IIS?

**Comment by LastTribunal** [comment]
yes

**Comment by baileyjames9** [comment]
Did you ever find a resolution? I seem to be following in your footprints here. Server = iis 8.x windows 2012 sr2, client = windows forms + signalr 2.2

**Comment by zhikin2207** [comment]
I have the same issue which is still not solved.

**Comment by baileyjames9** [comment]
Windows 8 or 10 is required for a Windows client to connect over websockets. Websockets on iis requires Windows 2012 server with websockets configured. My issue was the client I had was Windows 7.

**Comment by zhikin2207** [comment]
I am using windows 10 universal apache cordova for client.

**Comment by zhikin2207** [comment]
And I am using Windows server 2012 R2 + IIS 8.5 with enabled websocket protocol.

**Comment by Bill-P** [comment]
Any more movement here?

We also have Windows server 2012 R2 + IIS 8.5 with enabled websocket protocol.

**Comment by moozzyk** [comment]
This issue is lacking enough details to be able to tell what's going on. In the original report the client threw PlatformNotSupportedException. This means that webSockets on the server was enabled and after negotiating the client tried to open a webSocket which failed due to the client not supporting webSockets. There is no details about the client. @zhikin2207 reported that he sees something similar with apache cordova but he did not provide details about the server and also I believe he is using a different client so hard to tell if this is "the same issue". 
I am closing this issue since there is not enough details here. Feel free to open a new issue with all the details that may make it possible to figure out what is happening.
