### ISSUE TITLE
TaskAsyncHelper.Delay subtle bug

### ISSUE THREAD

**Issue by GSPP** [SignalR/SignalR#3505]
TaskAsyncHelper.Delay has a subtle bug. For reference, here the source code:

            var tcs = new TaskCompletionSource<object>();

            var timer = new Timer(tcs.SetResult,
            null,
            timeOut,
            TimeSpan.FromMilliseconds(-1));

            return tcs.Task.ContinueWithPreservedCulture(_ =>
            {
                timer.Dispose();
            },
            TaskContinuationOptions.ExecuteSynchronously);

First, a new timer is created and started. Then, `timer` is assigned. This means that `timer.Dispose()` can run *before* `timer` is assigned. This would cause a null reference exception.

The proposed fix is to check for `timer != null` before disposing. There's still a race but now it is benign.

**Comment by moozzyk** [comment]
Wouldn't the correct fix be to not to start the timer immediately but to start it after the `timer` variable has been assigned?

**Comment by GSPP** [comment]
Hm, yes that would be a precise fix.

**Comment by IanYates** [comment]
I'm sorry, and maybe it's because I've not had enough morning coffee, but I don't see the bug here.

Quote: First, a new timer is created and started. Then,  timer  is assigned. This means that  timer.Dispose()  can run before  timer  is assigned. This would cause a null reference exception

To expand on that, you really mean
A new timer is created and started.  Timer is assigned.  Then a continuation (one that references the local timer variable) is set up.  That continuation disposes of the timer.

The continuation which does the disposing doesn't even exist until after the timer variable is assigned.  What's the race?

In the worst case, assume timer fires immediately - before the timer variable is even assigned.  So it then completes the task completion source.  Job done.
Then the timer variable is assigned.
Then the continuation is set up.
At that time the timer variable is referenced and its Dispose method is invoked.
Still not a race.

I could well live to regret this post - please point out what I've missed and I'll gladly eat that humble pie :)

**Comment by GSPP** [comment]
The pie goes to me. There is no bug :)

It actually is rare to find a completely correct implementation of Task.Delay. I have seen code that is broken in the way I described. For some reason I thought that the same problem applied here as well.

**Comment by IanYates** [comment]
No problem - I've always got plenty of pie to share! :D
