### ISSUE TITLE
https self host

### ISSUE THREAD

**Issue by Shahrooze** [SignalR/SignalR#3541]
Hi.
I have a problem with https on self host in SignalR .When we use https in SignalR app with port 443 every thing is OK.But when we use any other port we get ERR_TUNNEL_CONNECTION_FAILED. 
I test it on IIS with default port and other port but every thing is good.I don't know is it related WITH SignalR  or related with other OWIN host?

**Comment by 12343954** [comment]
hi， @Shahrooze ， have you solved it ？i have the same problem

**Comment by anurse** [comment]
@12343954 This issue was closed a while ago, so I'm not sure what the history is. Can you file a new issue if you're seeing a problem? Please double check if standard HTTPS requests are working (i.e. not using SignalR, just standard requests for pages). If those requests are working but SignalR requests are failing, then there may be a SignalR issue to investigate.
