### ISSUE TITLE
Unable to Connect SignalR WPF client with Web based Server

### ISSUE THREAD

**Issue by eyemzubair** [SignalR/SignalR#3546]
Dear Team,

I have hosted Web based SignalR server on IIS (http://10.144.70.113:88/) Its working fine but when i am trying to connect my WPF client then its unable to connect with SignalR server

Its quite Urgent we need to fix this problem on high priority, Please reply me back asap

**Comment by IanYates** [comment]
You might have more luck on Stack Overflow as you're asking a question rather than reporting a bug/issue.

When posting on Stack Overflow you'll also want to include information such as .NET framework version, SignalR version, error messages you're receiving, IIS version, etc.  It may even be worth doing a bit of proxy interception with Fiddler so you can see what kind of traffic (if any) is flowing between your WPF client and the server.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
