### ISSUE TITLE
"jQuery was not found. Please ensure jQuery is referenced before the SignalR client JavaScript file.",

### ISSUE THREAD

**Issue by livesankp** [SignalR/SignalR#3574]
Hello,

This is what i am doing with jQuery, jsdom and signalr.js file
//jsdom dependency of jQuery
var jsdom = require('jsdom').jsdom, document = jsdom('test');
global.window = document.defaultView;

//below is the suggestion from jQuery developers for work around
//https://github.com/jquery/jquery/issues/2642#issuecomment-147418785
global.XMLHttpRequest = window.XMLHttpRequest;

//jQuery
var $ = require('jquery');
$.support.cors = true;

//SignalR added externally, Configuration, Common functions, Constant
var signalr = require('./util/jquery.signalR-2.2.0.js'),;

This was a working code before i updated node to v4.1.2 and node_module jquery is v2.1.4 and jsdom is v6.5.1. All latest available versions.

After updates i am getting jQuery was not found error where as i was able to see $ was defined already and when it goes to signalr $ is undefined. 

Please advice if i need to change anything now with new versions.

**Comment by vandervidi** [comment]
@livesankp Did you manage to solve this? im getting the same error

**Comment by sankp** [comment]
//require
var jsdom = require('jsdom').jsdom, 
document = jsdom('test2', { agentOptions: { keepAlive: false }});

global.window = document.defaultView;
//test below line again new jQuery 3.0.0 module again
global.XMLHttpRequest = window.XMLHttpRequest;

//jQuery
var $ = require('jquery');
$.support.cors = true;
window.jQuery = $;

//SignalR added externally, Configuration, Common functions, Constant
var signalr = require('./util/jquery.signalR-2.2.0.js'),

**Comment by sankp** [comment]
@vandervidi I was able to resolve this at that time but it's been 3 years now and we have trashed this project so i don't have any latest update on this.

**Comment by nightmare233** [comment]
##-Please type you reply above this line-##
 
 Hi {!Ticket.Name} , 
  
 Thank you for contacting us! 
  
 We have received your query as below: 
  
 //require
var jsdom = require('jsdom').jsdom,
document = jsdom('test2', { agentOptions: { keepAlive: false }});

global.window = document.defaultView;
//test below line again new jQuery 3.0.0 module again
global.XMLHttpRequest = window.XMLHttpRequest;

//jQuery
var $ = require('jquery');
$.support.cors = true;
window.jQuery = $;

//SignalR added externally, Configuration, Common functions, Constant
var signalr = require('./util/jquery.signalR-2.2.0.js'),

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/SignalR/SignalR/issues/3574#issuecomment-363996966 
  
 To help track your query, we have generated a Comm100 Ticket Id. Your Comm100 ticket Id is S34008-T86. Please include this ticket number in all your communications with us. 
  
 We will resolve your query and contact you as soon as possible. 
  
 If you have any other question, please feel free to contact us. 
  
 Sincerely yours, 
  
 



CNaqH_OgpPM_haqJt

**Comment by nightmare233** [comment]
##-Please type you reply above this line-##
 
 Hi {!Ticket.Name} , 
  
 Thank you for contacting us! 
  
 We have received your query as below: 
  
 @vandervidi I was able to resolve this at that time but it's been 3 years now and we have trashed this project so i don't have any latest update on this.

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/SignalR/SignalR/issues/3574#issuecomment-363997410 
  
 To help track your query, we have generated a Comm100 Ticket Id. Your Comm100 ticket Id is S34008-T87. Please include this ticket number in all your communications with us. 
  
 We will resolve your query and contact you as soon as possible. 
  
 If you have any other question, please feel free to contact us. 
  
 Sincerely yours, 
  
 



CNaqH_OgpPM_haqJu

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
