### ISSUE TITLE
SignalR allows connection without negotiation

### ISSUE THREAD

**Issue by Svmali84** [SignalR/SignalR#3620]
As per my understanding SignalR client sends negotiation request first. In the negotiate request it receives JSON response which has connection details like connectionid,connectiontoken , Trywebsockets etc...Now client sends the connect request with received connectionToken in querystring. SignalR server establishes the connection.

Here is the hack I found while testing the application..If I directly sends reconnect request with any of the previously issued connectiontoken without negotiate request , server still allows the connection.Actually this should not happen. SignalR should allow the connection to the connectionToken which is actually issued by him.

**Comment by moozzyk** [comment]
SignalR uses the user name to create connection tokens during connection negotiation. If authentication is not enabled the user name is an empty string and as a result anyone who has the connection token can send any request to the server as the user who originally got the connection token. If you use authentication this won't happen since the server checks the name of the user sending the requests against the name from the connection token and if the names don't match the request will fail. You can find more details [here](http://www.asp.net/signalr/overview/security/introduction-to-security#connectiontoken)

**Comment by Svmali84** [comment]
Ok. I implemented custom authentication for my signalR application. As you said connectiontoken is generated using connectionid and name of the user. Now I implemented iUserIdProvider but the token is not getting generated using the username returned by my GetUserId method.
