### ISSUE TITLE
how to use  NumClients of  crank 

### ISSUE THREAD

**Issue by aazjcom** [SignalR/SignalR#3682]
when i use the command:crank  /NumClients:1 /Connections:1000 /Url:http://127.0.0.1:8088/signalr .it is ok.
but when i use the command:crank  /NumClients:100 /Connections:1000 /Url:http://127.0.0.1:8088/signalr .it is System.AggregateException: ---> System.NullReferenceException:  Microsoft.AspNet.SignalR.Client.HubConnection.GetUrl(String url, Boolean useDefaultUrl)
SignalR-dev\src\Microsoft.AspNet.SignalR.Client\HubConnection.cs: 216
Microsoft.AspNet.SignalR.Client.HubConnection..ctor(String url, Boolean useDefaultUrl) SignalR-dev\src\Microsoft.AspNet.SignalR.Client\HubConnection.cs: 38Microsoft.AspNet.SignalR.Client.HubConnection..ctor(String url)

**Comment by GodotGo** [comment]
me,to. I came across the same problem.

**Comment by moozzyk** [comment]
This is because when you have more than 1 client the ControllerUrl should be passed. The code does not check this and passes null when creating the hub (https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Crank/ControllerHub.cs#L66) which results in the NullReferenceException you are seeing.
