### ISSUE TITLE
Rewrite JavaScript bindings to no longer depend on jQuery

### ISSUE THREAD

**Issue by cburgdorf** [SignalR/SignalR#372]
The current JavaScript bindings rely on jQuery >1.5 to be included with the page. Since many people use different JavaScript Frameworks (e.g. dojo, extjs) it's not optimal to force people to additional include such a heavy library as jQuery just for signalR to work.

See also:
#371
#328

**Comment by jjfood** [comment]
Is this done yet? Really need this.

**Comment by syndicatedshannon** [comment]
I'd also like to see SignalR without jQuery dependency.

Side note: if I read this thread right, this issue has been the top SignalR feature priority for over 6 months with no comment during that time, and zero commits on the [new repo](https://github.com/aspnet/signalr-client-js) in that time. Strictly professionally, it makes me unsure about adding SignalR dependencies to my project.

**Comment by tedvanderveen** [comment]
@syndicatedshannon True +1

**Comment by RyanDansie** [comment]
+1

**Comment by Misiu** [comment]
This was asked on May 2012. As @syndicatedshannon  wrote, there is nothing in new repo.
Is it even possible to have this in 2015?
@DamianEdwards  any updates on this?

**Comment by larz91** [comment]
+1
27. jan. 2015 16:21 skrev "Tomek" <notifications@github.com> følgende:

**Comment by noobouse** [comment]
+1

**Comment by jasonwilliams200OK** [comment]
@halter73, @DamianEdwards, @NTaylorMullen, @davidfowl, @gustavo-armenta,

If someone submits a PR for this, will you guys even accept it?
Do you even recognize that there exists a demand to make SignalR JS client a top-level library, independent of jQuery? `window.signalR` instead of `$.signalR`. 

To convince someone that jQuery dependency in 2015 is not a good idea, here is another one: checkout when was the last time the original jquery creator `@jeresig` wrote the code: https://github.com/jquery/jquery/graphs/contributors. It was 2011! So please Do NOT use jQuery or anything similar (MooTools, underscore, whatnot) AT LEAST in the library development. We spend HOURS to develop jQuery-free native code and then SignalR ****s on the effort. If YOU don't care and in love with jQuery so much, then use it in your own projects, not in the library so to give choice to people who like to live with latest times (in which SignalR is rendering itself obsolete to do this very reason)...

**Comment by daniellmb** [comment]
+1

**Comment by goranobradovic** [comment]
+1 this just made me not use SignalR for my new project

**Comment by mdlar** [comment]
+1 @goranobradovic - we would love to use SignalR in our projects as well but since we are a pure JS shop we cannot use it. Depending on any external JS library like jQuery is completely out of the question.

**Comment by srivathsah** [comment]
+1

**Comment by Misiu** [comment]
@halter73, @DamianEdwards, @NTaylorMullen, @davidfowl, @gustavo-armenta guys could we at least get any information on this? 
SignalR is grate, but when we want to use it current implementation is forcing us to use jQuery.
This must definitively change, especially if You want to make SignalR more popular.

**Comment by DerKnerd** [comment]
@jasonwilliams200OK I get the feeling `@jeresig` has left kind of left jquery. So I wouldn't count that as an argument against it. It still is a team out of 40+ members.

But yeah, I agree no dependency on jquery would be nice, mostly because the you can use it in WebWorkers and similar. On the other hand I can understand why the depend on jquery, the are not only using web sockets, if I understand it right there are many different ways how you can connect to SignalR and I would bet it was easiest to accomplish that with jquery.

**Comment by jasonwilliams200OK** [comment]
@DerKnerd the lesson is: *if you want to use jQuery, use it in your project but do not make it a dependency in a widespread library code*. Try to get used to this idea, it will only give you a positive advantage.

**Comment by DerKnerd** [comment]
@jasonwilliams200OK I know, I didn't wanted to say it is good to make a jquery dependency ;) It was just the thought, this project is kinda old, so it is understandable that it depends on jquery.

What bugs me a bit, I don't see SingalR as a framework, which does UI manipulation and that is a point where I would say "Why jquery?" I fully see it, even nowadays, in projects like bootstrap.

@DamianEdwards Maybe the approach angular uses is useful for SignalR, just use jqLite and put it directly in your library.

**Comment by jasonwilliams200OK** [comment]
> I don't see SingalR as a framework, which does UI manipulation

Exactly! Besides Bootstrap is also getting obsolete with the upcoming web components era, where we will be able to consume components from different vendors (as opposed to tied to one forever!).

How about replacing the `jquery.signalr` it with TypeScript classes and package the compiled JavaScript output in releases? It will take care of old browser and ECMA5 compatibility and soon provide forward compatibility for ECMA6.. 

SignalR team can always ask the TypeScript team for some help, only if they are interested..

**Comment by tedvanderveen** [comment]
+1 @jasonwilliams200OK for suggesting Typescript :)

**Comment by Daniel15** [comment]
> Besides Bootstrap is also getting obsolete with the upcoming web components era

wat? Bootstrap is a CSS framework, I don't see how it relates to web components at all. Sure there's some (objectively low quality) jQuery plugins included but the majority of Bootstrap is its CSS.

**Comment by Misiu** [comment]
Any news? This feature was requested almost 3 years ago...

**Comment by LarsKemmann** [comment]
Folks... There are two scenarios here under which we're going to get any news on this. 1) The ASP.NET team makes enough progress that the SignalR v3 work can be staffed, or at least details promised... i.e. we wait until July/August. 2) One of us has the time to go do the work ourselves and submit a pull request.

I recommend we stop harassing the team - they're busy working on ASP.NET 5. :)

**Comment by DamianEdwards** [comment]
@LarsKemmann is correct. We're heads down on the SignalR C++ client and ASP.NET 5. We hope to tackle the JS client as soon as we've wound up work on getting SignalR v3 (for ASP.NET 5) done.

**Comment by LarsKemmann** [comment]
@DamianEdwards Fantastic. :)

**Comment by mguadarrama** [comment]
+1

**Comment by ppumkin** [comment]
+1 we have client scripts that need to be small an till now avoided including jQuery and just using pure JS to minimize footprint. Ill just have to write some simple polling separately until the client initiates full app that is launched in a frame. We want to minimise load time for clients.

**Comment by tedvanderveen** [comment]
Maybe it's an option to use jqLite? A much more compact library that covers a subset of jQuery.
https://github.com/angular/angular.js/blob/master/src/jqLite.js
Added bonus for AngularJS projects that use SignalR that jqLite comes built in.

**Comment by ppumkin** [comment]
@tedvanderveen , Ahh very good alterantive! But, I just finished implemented minfying and gzip :) I get 32kb of jQuery 1.10 .. the same size of the jqLite file. I rather stick with the full jQuery. I made a script that checks if the client already has jQuery loaded, if not I pull my own jQuery file in, then SignalR and then do what I need to. Combined its about 90kb with Jquery 1.10 and SignalR 2, minified and gzipped.

**Comment by tedvanderveen** [comment]
@ppumkin jqLite would be 5kb minified&gzipped. Plus much less JS code that the browser needs to load/initialize.

**Comment by tedvanderveen** [comment]
NPM ref: https://www.npmjs.com/package/jqlite
And like I said, it may make SignalR a better fit for AngularJS projects as that comes with jqLite built in.

**Comment by ppumkin** [comment]
Yup, that is actually really great.  Atleast there are some options that a dev team can make now. For myself, I preffer to load the entire gzipped jQuery, because then I can use it on the script that loads on the client to do all the nasty business. I tried not to use to keep it small... but if it loads once then its cached, no problem for me. If we change all out sites to load from a specific jquery CDN, then any site the user visits, will cache it and we don't even need to re download it again, as long as we use the same "src" each time. We got many apps integrating all over the place.

But if the absolute requirement is to minimize the download footprint, then, absolutely, your jqLite suggestion is great and I will keep it in mind too.

As I said before though, I preffer the SignalR team get on with new features in SignalR and not waste time with the client script, because the jQuery team know what they doing. Everybody works in tandem and the web is becoming a great place to be in.

**Comment by tedvanderveen** [comment]
@ppumkin I very much respect your view here, and on fast enough machines and proper CDN usage, it does not really have a big impact to use JQuery. But I still find it kinda abusive to depend on a huge library like JQuery if only 1% of it's functionality is actually used. The browser does have to load and initialized the other 99%.
This is an issue specially when developing for older/less powerful (mobile) devices or low-bandwidth (mobile) connections.

**Comment by ppumkin** [comment]
@tedvanderveen I feel your pain, I suppose if I really needed to deliver compact files I would have a really difficult task ahead of me, re factoring SignalR and  jQuery, breaking maintainability. 

I suppose the problem, in essence is that it has a hard dependency on jQuery, period. I think if the SignalR team dedicate some time to maybe, remove the hard dependency on jQuery and allow an alternative library to be loaded, which implements the core functionality. Because if I went and found all the methods SignalR needs, and create my own namespaced library, I still have to call it $.jQuery otherwise signalR wont load, even though the implementation is exactly the same, just stripped down. 

In C# for example this can be be easily achieved with Interfaces, IoC and DI. But we are talking about scripting languages here. 

I suppose an easy fix, would be to accept an extra option during SignalR construction, to change the namespace it is calling the methods from (or by default leave jQuery), so that a lean library can be maintained by open source or created by developers. This would even allow for middle ware "interfaces" to be made, for example create a file that maps calls to another library and back, for the truly advanced.

So this would allow us to deliver minimum scripting with the highest scrutiny for bandwidth, without breaking signalR, allow the developers to extend core methods to do things they wanted instead of standard jQuery implementations or just use jQuery if we wanted to by default.

I think if the SignalR team can do this, they will be paving the road for many other scripts that rely on this library or that library and nothing else, instead of allowing us to choose what will implement the core functionality.

**Comment by LarsKemmann** [comment]
(sigh) One more time. @ppumkin and @tedvanderveen -- did you bother to read Damian Edwards's comment? **They will get to it. If you need something immediately, do it yourself.** Preferably correctly, removing any 3rd-party library dependency at all, and then submit a PR like David Fowler suggested, oh, three years ago next month? :-)

(As a gentle reminder, most of us pay exactly $0 for the benefit of using the SignalR team's hard work.)

To any future +1ers - unless you have something valuable to contribute, **please don't spam the developers** with unnecessary arguing for the merits of doing something that they have already expressed interest in doing for a long time.

**Comment by ppumkin** [comment]
We Just debating. I saw the comment and many more +1 after it. Like pages.
Just put a final statement and close this thread.

Thanks SingnalR team. This is truly amazing what you all have done. Sorry
for the spam.

**Comment by syndicatedshannon** [comment]
@LarsKemmann : Speaking only for myself here, my comment was about the lack of information. If someone announced this was postponed indefinitely, then it might make sense for someone else to step in and contribute, as you suggested. Until then, it's hard to know what to do. The last comment I saw here from Damian Edward was that it was a top priority, was being moved to a linked repo, and the provided link was still empty a year later.

Regarding "most of us pay exactly $0", my impression from the "Copyright (c) Microsoft Open Technologies, Inc." was that this is an MS-backed product, and therefore indirectly funded by our investment in our platforms. My apologies if I got that wrong, but you can see where the confusion might arise.

I was simply concerned about the future of the product. My choice to use it was based partly on the very MS backing I thought it had. That means, to me, that I don't have to debate whether or not I have any right to have consumer-type expectations about the stability and predictability of the product. If that backing had dried up, I wanted to make other choices.

I mean no offense by any of this, and would love to know if I'm misunderstanding.

**Comment by syndicatedshannon** [comment]
Also, thank you very much @DamianEdwards for the update.

**Comment by am11** [comment]
@LarsKemmann, with that logic VS, ASP and .NET teams use Newtonsoft's JSON.NET in their products (yes VS2013 and 2015 is using JSON.NET for built-in JSON editor because .NET team failed to implement as versatile standard JSON parser as JSON.NET), we can say that Microsoft paid $0 to that guy who singlehandedly has worked hours on open source repo and entertain hundreds of requests of people using his software directly or indirectly. That argument doesn't hold in opensource arena!

I will repeat my question: is SignalR team ready to take pull request in this repo? If so, please reopen this issue and add a tag "accepting PR" (like what TypeScript team do) and see how many and how fast you get this "average" feat sorted out! Closing this PR and playing hide-and-seek is the main source of confusion here in case you are missing it..

**Comment by LarsKemmann** [comment]
I knew I would pay for adding that remark... :) @syndicatedshannon, my point was that the team has publicly acknowledged the need and clearly intends it as a priority for post-SignalR V3 work. Of course SignalR is supported as part of the ASP.NET platform (the team already publicly committed to V3 last summer), and if this was a critical issue it would have received more direct attention.

The fact that it's been a known issue for 3+ years - and in all that time no one has posted a fix here - suggests that people have been making do and there are at least some manageable workarounds. Not ideal, maybe not even "good", but by and large acceptable.

@am11, if you want to submit a pull request, be creative and find a way. Fork and post a link, see if they don't reopen the issue and merge your fix. Sure it would be nice if they reopened the issue and tagged it, but they've been clear that it's going to be fixed in a different repo in the future. No one is "playing hide and seek" here.

**Comment by tonymayoral** [comment]
+1

**Comment by oliverjanik** [comment]
+1

**Comment by jasonwilliams200OK** [comment]
> No one is "playing hide and seek" here.

Matter of fact, they are doing poor job making us believe otherwise!

> be creative and find a way

Your own advice applies to you as much as anyone else :)

**Comment by groovy21** [comment]
+1 please. This has been ignored for a long time now.

**Comment by avanderhoorn** [comment]
As a note for others not using jQuery for anything else, if you are using WebPack, you can use [this](http://alexomara.com/blog/webpack-and-jquery-include-only-the-parts-you-need/) technique to just load in Deferred, Ajax and Events modules. Should cut down on what you are bringing in quite a bit (i.e. not sizzle, dom stuff, etc).

**Comment by tedvanderveen** [comment]
@avanderhoorn interesting! Would that technique also allow for trimming down on jQuiry bloat even furtherfor functionality that is already available through jQLite (which comes with Angular)?

**Comment by avanderhoorn** [comment]
Great question. I would have to do a test. I use underscore/lodash for
other things in my app and I've been thinking of having a proxy which goes
through to it instead, but at this point in our dev cycle just getting it
working is enough and knowing that it can be trimmed down.

**Comment by Cliveburr** [comment]
+1

**Comment by anuccio1** [comment]
+1

**Comment by DJHightower** [comment]
+1

**Comment by jquense** [comment]
So are switching over to React, and including all of jquery for just signalR is not super acceptable. Luckily SignalR relies on a very small subset of jquery, so its pretty easy to shim out for anyone else in the same situation as us

I hand waved past ajax a bit, but you can find a bunch of jquery compatible xhr libs like component-ajax on npm. Sorry its all in ES6 javascript

```js
import ajax from './ajax';
import Promise from 'bluebird';

function fakeQuery(subject){
  let events = {};

  if (subject && subject === subject.window)
    return {
      0: subject,
      load: (handler)=> subject.addEventListener('load', handler, false),
      bind: (event, handler)=> subject.addEventListener(event, handler, false),
      unbind: (event, handler)=> subject.removeEventListener(event, handler, false)
    }

  return {
    0: subject,

    unbind(event, handler){
      let handlers = events[event] || [];

      if (handler){
        let idx = handlers.indexOf(handler);
        if (idx !== -1) handlers.splice(idx, 1)
      }
      else handlers = []

      events[event] = handlers
    },
    bind(event, handler){
      let current = events[event] || [];
      events[event] = current.concat(handler)
    },
    triggerHandler(event, args){
      let handlers = events[event] || [];
      handlers.forEach( fn => fn.call({ type: event }, ...args))
    }
  }
}

window.jQuery = Object.assign(fakeQuery, {
  ajax,
  noop(){},
  isFunction: o => typeof o === 'function',
  isArray: arr => Array.isArray(arr),
  type: obj => typeof obj,
  trim: str => str && str.trim(),
  extend: (...args) => Object.assign(...args),
  each: (arr, cb) => arr.forEach((v, i)=> cb(i, v)),
  isEmptyObject: obj => !obj || Object.keys(obj).length === 0,
  makeArray: arr => [].slice.call(arr, 0),
  Deferred(){
    var resolve, reject;
    var promise = new Promise(function() {
      resolve = arguments[0];
      reject = arguments[1];
    });

    return { resolve, reject, promise: ()=> promise };
  },
  support: {
    cors: ('withCredentials' in new XMLHttpRequest())
  }
})
```

**Comment by jasonwilliams200OK** [comment]
The idea is to "break" the dependency on jQuery. Shimming the jQuery features with a "slim version of jQuery" will be a bad idea IMO because it will mislead people to think "SignalR already includes jQuery library, so I don't need to include it separately and still use jQuery in other parts of project". Trust me, an average .NET developer is full of misleading concepts about JavaScript.

Starting over with independent "new SignalR()" kind of sleek API without even impregnating `window` is the best way to go here. Providing node.js style callback for async signatures would be a big plus!

```javascript
var SignalR = require('SignalR'); // for commanJS (node.js compatible) / requireJS etc.
// a good library provides both patterns, with and without the above line

var signalR = new SignalR();
var options = signalR.fetchOptions(); // returns some options object {}

/// sync version
var result = signalR.someFuncSync(options);

if (result.error) {
   // throw / log and return etc.
}

// now do something with result

/// the async version
signalR.someFunc(options, function(err, result){
  if(err) {
     // throw / log and return etc.
  }

  // now do something with result
});
```

AFAICS, this style is very popular among people familiar with node.js. This approach is also popular with those JS libraries which entertain both with and without module-loader targets. Reinventing new conventions / styles etc. or sticking with old-school jQuery style does not help fixing this situation. (there are how many, like over a billion npm packages out there using this pattern, right? and every morning you get like 1000 new packages.. sounds to me like no rocket science here!!)

This also means (retired) people who want to use jQuery will still be able to jQuerify the plain `signalR` object (`$(signalR)`).


# So please, at least:

# NO JQUERY DEPENDENCY OR JQUERY-LIKE *ANYTHING* WITHIN YOUR LIBRARY IMPLEMENTATION!

**Comment by Daniel15** [comment]
> Providing node.js style callback for async signatures would be a big plus!

Callbacks aren't really ideal, you can easily get into callback hell with callbacks inside callbacks inside callbacks. We have better patterns now, and SignalR should be treated as a modern library. Async/await or at least promises is where it's at now.

**Comment by Daniel15** [comment]
@jasonwilliams200OK 

> Shimming the jQuery features with a "slim version of jQuery" will be a bad idea IMO because it will mislead people to think "SignalR already includes jQuery library, so I don't need to include it separately and still use jQuery in other parts of project"

I think @jquense is just doing that so he can use the current version of SignalR without bundling jQuery or modifying SignalR's JavaScript library itself. He didn't mean to suggest actually bundling a jQuery shim with SignalR itself :) 

> Providing node.js style callback for async signatures would be a big plus!

Callbacks aren't really ideal, you can easily get into callback hell with callbacks inside callbacks inside callbacks. We have better patterns now, and SignalR should be treated as a modern library. Async/await or at least promises is where it's at now.

**Comment by jasonwilliams200OK** [comment]
@Daniel15, thank you for "quickly" nitpicking on the "hellish" parts of my proposal on 2012 post, which eveidently nobody at @Microsoft care about. And thank you for ignoring the fact I am highlighting that if there are over a million libraries doing one way and SignalR embracing that pattern will **not** be a fiasco!

> Callbacks aren't really ideal

You said it twice. I have no idea where you are coming from, but I wouldn't jump to this conclusion..

Regarding callback vs. promises (proposed for Ecma6 ?) and RxJS (proposed for Ecma7 ?) etc., I have no objection, but if your library is riding the node-style callbacks bandwagon today, there will definitely be an upgrade path to promises pattern and then to reactive extensions, when those will get adapted by wide range of browsers, node.js, atom-shell runtimes. Today using promises means "another" dependency to polyfill IE8,9 etc.

I hope you know as much as I do that this is not the first discussion happened on github about callback, promises RxJS. But if you insist, we can invite more "credible" people here and further delay the real matter at hand. 

So please chill!

**Comment by jquense** [comment]
> I think @jquense is just doing that so he can use the current version of SignalR without bundling jQuery or modifying SignalR's JavaScript library itself. He didn't mean to suggest actually bundling a jQuery shim with SignalR itself

lol yes of course. the code is for anyone who can't wait for SignalR to not include jquery, and want the least intrustive way of getting it to work without jquery. Obviously signalR itself should not ship a shimed jquery lite...

The other point was just to illustrate how little of jquery the js client actually uses, it doesn't do any DOM stuff (except for window.load) so the idea that there is some large cross browser interop issue requiring jquery is not true.

**Comment by Ixonal** [comment]
sooooooo over a year since this issue was closed, and the repo that was listed is still empty and hasn't been updated since May... Is anyone still looking at this issue, or is it a sort of zombie?

**Comment by benjamineberle** [comment]
+1

**Comment by ppumkin** [comment]
Its not going to happen.. just let it go... and load jquery, or jquery
lite, or check if the client has jquery already loaded.

**Comment by syndicatedshannon** [comment]
#3565

perhaps all ms members unsubscribed from this issue after it was closed, and are simply unaware that a lot of people still desire a formal place to follow status on it.

the problem is the trail of authoritative comments sets expectation for further information that has not materialized

**Comment by sharizard** [comment]
+1

**Comment by wilgert** [comment]
+1

**Comment by austinsc** [comment]
We are currently working on a rewrite of the SignalR JS library using ES6 and javascript modules. It is still definitely a work in progress, but we hope to have a stable build within the next couple of weeks. We are also working on a new generator that will produce [Redux](https://github.com/rackt/redux) action creators and action types for both server and client side calls (when using Hub<T> base class).

https://github.com/RoviSys/signal-arr

**Comment by BlueInt32** [comment]
@austinsc this looks great ! do you have any sample to show before the docs come out ?

**Comment by jasonwilliams200OK** [comment]
@austinsc, great work! Instead of ES6, can we have a old ES code files to keep it compatible with IE7+?
I don't think there is much code which needs ES6 features. You can then do a pull request here with zero breaking changes. :)

**Comment by ppumkin** [comment]
http://blog.delib.net/3-reasons-you-need-to-transition-off-ie7-and-ie8-asap/

No, stick with ES6 and stop supporting obsolete stuff, otherwise you just creating another anchor to stay in the past. jquery 2 dropped all the old garbage. If you want to support obsolete software, do it at your own cost.

**Comment by jasonwilliams200OK** [comment]
> No, stick with ES6 and stop supporting obsolete stuff,

How about IE9 and IE10? They don't support ES6 either. Dropping jQuery is the focal point here, not orphaning majority browsers!

**Comment by ppumkin** [comment]
They getting nuked soon too. I stopped supporting IE because it was frying my brain. My job, as a developer is allot easier now. IE cant be the root cause of not going forward. Cut the cord loose and all of a sudden there are beautiful solutions. Somehow any other major browser does not have this issue....

> not orphaning majority browsers

Seriously? You must be a government contractor in China.

**Comment by jasonwilliams200OK** [comment]
What issue really?
Have you even seen SignalR javascript files?
They don't need anything ES6 or ES7 features. But if you want to screw things up as a mission then that is a separate story.

**Comment by wilgert** [comment]
@jasonwilliams200OK You can transpile to ES5 so what's the problem?

**Comment by zardoz** [comment]
@wilgert 

This is totally correct, It's called Babel. 

@ppumkin 

Also totally correct, from personal experience, please do not be afraid to tell you customers to join the 21st century, we did and now most of our customers are on Chrome, FF, Opera or even IE 10+. If you don't you are just pandering to their laziness and paying for it dearly.

Good work guys, you are making the right decision in implementing ES6, keep it up.

**Comment by ppumkin** [comment]
:+1:

**Comment by jasonwilliams200OK** [comment]
@zardoz, IE10 and even Chrome does not implement full set of ES6. If you tell any library developer (try lodash for example) to switch to ES6 just for fun, while the code can sgtill easily be written with ES5 in favor of Babel, I don't think you would convince anyone in 2015.
Besides, SignalR's JS client provides long polling fallback for communication with old browsers, going by your logic, should we also remove that feature (since the latest greatest browsers implement WebSocket and friends)? *As a library*, dropping the support just to make code look sexy (`function () {}` vs. `()=>{}`) is NOT the very famous trait. For homebrew project, yes I love breaking things and hating IE too.

**Comment by ppumkin** [comment]
ES6 cant support long polling?

Change can be difficult for some.

**Comment by jasonwilliams200OK** [comment]
@ppumkin, long polling is an "old" technique for fallback purposes. You are missing the whole point.

**Comment by jquense** [comment]
Can you all have this conversation elsewhere? Every time you each misunderstand browser support, transport methods, ES6 and transpiling you notify like a 100 people. please just talk on IRC and leave this conversation to the dang topic

**Comment by Ixonal** [comment]
@austinsc Great news. I can't wait to see it in action. Out of curiosity, any reason for not using TypeScript (as long as you're doing transpilation anyways)?

**Comment by jasonwilliams200OK** [comment]
Haha nice image on your repo @austinsc 

<img alt="signal-arr" src="https://camo.githubusercontent.com/9f73c24e5d8d456e5834b1efcb82284da1fc4025/68747470733a2f2f63646e2e7261776769742e636f6d2f526f76695379732f7369676e616c2d6172722f6d61737465722f646f63732f7369676e616c2d6172722e737667" data-canonical-src="https://cdn.rawgit.com/RoviSys/signal-arr/master/docs/signal-arr.svg">

**Comment by austinsc** [comment]
Thanks guys, things are moving forward. We are using babel to transpile, so
es5 code output is an option. Since we are building this for a specific
project, things like docs are in the works- sorry for the delay. Also, I
recommend checking out https://github.com/rovisys/signal-arr-proxygen . It
is a node.js based replacement for the built in
DefaultJavascriptProxyGenerator class. You can incorporate it into your
build system to scan a .net assembly and pull out the hub client code.

**Comment by mchambaud** [comment]
@ppumkin WebSocket can also be a server side limitation. Imagine a website behind a load balancer which only supports HTTP.

**Comment by austinsc** [comment]
@Ixonal heh, the comments probably wont get shipped that way

**Comment by MaheshKalyankar** [comment]
Guys please help me... is there any way to write SignalR with Dojo library  or Pure JavaScript..? i need to do a POC for SignalR with Dojo library so is there any way to do so i can start something. I am new to SignalR and Dot Net

**Comment by dlebedynskyi** [comment]
@austinsc  would love to see this project live. Any change to actually add typescript definition?

**Comment by austinsc** [comment]
I've finally got some breathing room to keep this moving forward. I'll look into what it would take to get the typescript definitions created. (pull requests are welcome ;). AFAIK everything works, you should be able to download and run the tests which actually contact a demo server on the internet.

**Comment by dlebedynskyi** [comment]
@austinsc  do you mind adding read me ?and some examples ) I do assume this is right repo https://github.com/rovisys/signal-arr-proxygen

**Comment by austinsc** [comment]
@dlebedynskyi check out [https://github.com/rovisys/signal-arr](https://github.com/rovisys/signal-arr). Documentation is in the works, and so are additional samples. You can always check out the tests for information on how to use it.  [https://github.com/rovisys/signal-arr-proxygen](https://github.com/rovisys/signal-arr-proxygen) is for generating the client side proxies from a binary so that they can be used in a front-end build system like webpack or browserify.

**Comment by lbacaj** [comment]
+1 for getting rid of the jQuery dependency 

Let's do it already the whole community is moving away from this thing, it has passed its time.

**Comment by nukuuk** [comment]
+1

**Comment by dlebedynskyi** [comment]
@austinsc  tried to use your libs. no luck so far. hope to see good no JQuery implementation someday. 
maybe with release of new signalR version. For now we just switched  to pure websocket with simple group management. turned to be easier for us.

**Comment by riza-herzego** [comment]
+ 1

**Comment by amcdnl** [comment]
+1

**Comment by syndicatedshannon** [comment]
I'd just like to mention. I do not hold the development team personally responsible for this, and mean no disrespect to individuals.

And yet, I definitely hold Microsoft, its SignalR product, and its SignalR product management, accountable for this. Communication on this has really been botched, and the resulting inability to plan correctly has diminished the quality of products I've created.

I get that this product is "free". Except it's not.

**Comment by scottaddie** [comment]
+1

**Comment by Michsior14** [comment]
+1

**Comment by jasoncavaliere** [comment]
+1 
I'm going to hack together something, but would prefer not to.  I really like the simplicity on the server side, but I'm not ok with including jquery any more, this is ridiculous...

**Comment by DamianEdwards** [comment]
We're about to start the investigation into this over on the new repo now that ASP.NET Core 1.0 is released. Thanks.

**Comment by Misiu** [comment]
@DamianEdwards great news! Can't wait for jquery-free version!

**Comment by dlebedynskyi** [comment]
@DamianEdwards just as idea - it would be great to have signalR compatible with express.js client. 
Might be even good if you guys separated client and server into separate repos, to avoid scenario this.

**Comment by dkrishnap** [comment]
We implemented signal R in SL4 using javascript without moving to SL5 . Now the problem we are getting with Out of browser app in SL due to javascript is not loading because of Default.aspx file is not invoked which is web browser related. Can you please suggest any solutions how we can implement in OOB app using Javascript or any other options. If possible can you please give a sample how we can implement signalr client using websockets using WCF.

Please help.

Thanks
Krishna

**Comment by Ponant** [comment]
@DamianEdwards That will be great and timely now that .Net Core passed an important milestone.

**Comment by kenotron** [comment]
@DamianEdwards can you link to the new issue you're tracking this on the new repo?

**Comment by PterPmnta** [comment]
@DamianEdwards  when come out SignalR without jquery?

**Comment by nukuuk** [comment]
About every six months I check this repo.  And about every six months I see nothing is moving forward.

**Comment by rhummelmose** [comment]
.......?

**Comment by chriscerk** [comment]
For others that are frustrated:

Appears that new SignalR for .NET Core doesn't rely on jQuery.
[aspnet/SignalR](https://github.com/aspnet/SignalR)

**Comment by DVLP** [comment]
Here's my version which doesn't pollute window object with jQuery and locally uses bare-minimum jQuery shim which adds only ~5kb instead of typical 90 https://github.com/DVLP/signalr-no-jquery

**Comment by raybooysen** [comment]
@DVLP Is this using the latest release of SignalR?  Do you know if it works with all the fallbacks?

**Comment by DVLP** [comment]
@raybooysen it's using the latest v2.2.1 , everything is included. There are no changes made to signalR code(except of replacing window.jQuery in wrapping closures) and jQuery shim is taken from react-native-signalr so if everything went right it should all work.

**Comment by drcmda** [comment]
@nukuuk we're observing this issue (and others like module imports & npm) for years now and nothing is happening. Why we didn't go to SocketIO+uWebSockets in the first place i do not know.

**Comment by hakimfg** [comment]
Its such a nice thing Signalr. But dependecy on Jquery is one thing that is making us reconsider to use signalr in our project.

**Comment by jamesomitron** [comment]
Well, since we are waiting for the signalr independent of jquery, does anyone know how I can take my signalr requests and broadcast off the UI thread? its stalling my pages

**Comment by mentinghfreightcenter** [comment]
Meanwhile, 4 years later, still no SignalR without jQuery dependency.

**Comment by WillFM** [comment]
@mentinghfreightcenter, this is an open source repo, your more then welcome to take up the task, and send in a pull request, I'm sure the SignalR team would be more then willing to accept any meaningful pull requests. I'm actually surprised that no one has at this point for this flavor of SignalR. on the flip side, the version of SignalR being developed along side .net core, actually has a flavor the the SignalR client that does not have the JQuery dependency, your welcome to go check it out at: https://github.com/aspnet/SignalR

**Comment by mentinghfreightcenter** [comment]
Awesome, thank you for the info. I also found a github repo that makes signal R believe jquery is installed while using a jquery shim library: [https://github.com/DVLP/signalr-no-jquery](https://github.com/DVLP/signalr-no-jquery)

**Comment by moozzyk** [comment]
@WillFM @mentinghfreightcenter - the client in the https://github.com/aspnet/SignalR repo won't work with 2.x server.

**Comment by sreekumarp** [comment]
+1

**Comment by sag1v** [comment]
> On the flip side, the version of SignalR being developed along side .NET Core, actually has a flavor of the SignalR client that does not have the JQuery dependency, your welcome to go check it out at: https://github.com/aspnet/SignalR
@WillFM I hope that this is not the reason why we won't get an asp.net (not core) version of signalR without the jQuery dependency.

**Comment by JohnGalt1717** [comment]
The question is how to use the .net core signalR with .net full owin and make it work without having to redo our entire api ported to .net core...

**Comment by moozzyk** [comment]
SignalR Core is not compatible with SignalR 2.x - i.e. you will not be able to use SignalR Core client with SignalR 2.x server and vice versa.

**Comment by JohnGalt1717** [comment]
So in short this will never get fixed. Someone should just put this ticket out of it's misery and close with won't fix.

**Comment by WillFM** [comment]
@JohnGalt1717, this ticket has been closed for 3 years now.

**Comment by JohnGalt1717** [comment]
It was closed because it was supposed to be in version 3. Version 3 isn't happening obviously and it needs to be made clear by MS that this will never be addressed in the .net full fat version because it's abandonware at this point.

**Comment by WillFM** [comment]
@JohnGalt1717 that's a bit of a misnomer. Just like ASP.NET 5 was renamed ASP.NET Core. SignalR 3 was renamed SignalR Core.

**Comment by JohnGalt1717** [comment]
That's BS. Signalr 3 was supposed to be full fat .net framework and fix this. Now .net framework 4.x is left with abandonware and SignalR that requires jquery for no right what-so-ever.

So the only way you're going to get the fixed version of the client library is by spending a month porting your project to .NET core.

*headbang*.

**Comment by halter73** [comment]
@JohnGalt1717 ASP.NET Core 2.0 still runs on .NET 4.x in addition to .NET core in case you aren't aware. You might still need to port your app to the new ASP.NET framework, but at least most of your .NET 4.x dependencies should still work.

**Comment by JohnGalt1717** [comment]
Given that the entire pipeline for ASP.NET 5 and sockets is completely different I strongly doubt that it will work. But hey, if someone from MS wants to chime in on their own project and demonstrate that this isn't abandonware and tell us one way or another, that would be great!

**Comment by mentinghfreightcenter** [comment]
I also believe that Signal R for ASP.NET 4.x has been abandoned. Such a shame...

**Comment by stannynuytkens** [comment]
Seriously, this is abandoned? And on the .Net core version they state not to use it in production code.. Also shame that they don't continue working on a more bare client js library (without jquery). In todays web development with Angular, React, Vuejs, ...

**Comment by ppumkin** [comment]
SingalR Core (without jQuery dep) works great on DotNetCore .. Common guys.. Time to move on now. This is what you wanted all along. I am happy.

**Comment by davidfowl** [comment]
> Asking users to write it themselves and send a pull request is not only ridiculous but outright irresponsible.

You're right, that was wrong. I should have been more honest about this. We have no plan to do this work.

**Comment by syndicatedshannon** [comment]
"should have been more honest" is only part of the issue, speaking as one following this thread for 6 years.

**Comment by dungmv** [comment]
how can use signalr on react-native?
I can't move signalr to signlr ccore
