### ISSUE TITLE
Hub client is not aware about server Side Hub-disconnect

### ISSUE THREAD

**Issue by vivek0685** [SignalR/SignalR#3785]
Hi All,

I am facing the issue  related to SignalR Timout/Disconnect. **Due to unknown reasons Hub Server side OnDisconnected(bool stopCalled) event is fired with stopCalled=false but client is not aware about disconnect happened at server side and still client side connection state is connected .**I am using C# client for connectivity.

Please let me know if you have any solution for this.

**Comment by vivek0685** [comment]
Any update on this?

**Comment by moozzyk** [comment]
This issue does not contain enough details to be actionable and does not indicate a bug in SignalR. 
On the server side `OnDisconnected(false)` is called if the client connection was lost and the client did not reconnect within a timeout. So, the client is never aware of the server invoking `OnDisconnect` - either the client closed the connection explicitly (stopCalled -> true) so it does not receive notifications any longer or the server lost track of the client (stopCalled -> false) so it can't send any notification to the client. 
This can also happen if you have multiple server and the client reconnected to a different server (see: https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Hubs/HubBase.cs#L46)
Note that unless you disabled keep alive messages or tweaked timeouts if the client lost connection to the server (e.g. due to network issues) it should notice that the connection is dead in matter of seconds (if you are using websockets or serversentevents and up to 2 minutes if you are using long polling). 
Also, check if you don't have any reconnect logic on the client - maybe you reconnect (e.g. when an error happens) and therefore you create a new connection while the other one gets abandoned and eventually times out on the server.
