### ISSUE TITLE
Deserialization Vulnerability - Medium

### ISSUE THREAD

**Issue by immi5556** [SignalR/SignalR#3796]
As a part of penetration test, Modifying the connectionData parameter of the HTTP request as shown in the following URL:
http://*******..com/signalr/connect?transport=webSockets&connectionToken= QTljTm4xMC9Ia2thRUdOeTdPdXRhMkppMnZvVldL&connectionData=%20999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999%20&tid=7 causes the server to return an error message which includes the following statement, “System.ArgumentException: Could not cast or convert from System.Numerics.BigInteger to System.Collections.Generic.IEnumerable”

### Expected  behavior 
 - Options for developer to override function to capture the request and  send appropriate response or handle the error by signal R

### Actual behavior
- It is throwing error before validating the issue..

### Steps to reproduce
use the below url in any signalr hosted website, 
http://*******..com/signalr/connect?transport=webSockets&connectionToken= QTljTm4xMC9Ia2thRUdOeTdPdXRhMkppMnZvVldL&connectionData=%20999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999%20&tid=7

**Comment by moozzyk** [comment]
connectionData is a url encoded JSon array containing a list of hubs. You changed the array to a number which apparently was parsed by JSon.Net as a BigInteger. The (code requests that JSon.Net returns IEnumerable)[https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Core/Hubs/HubDispatcher.cs#L109]. Since it's not possible JSon.NET throws an exception. 
I don't see any vulnerability here. connectionData is internal to SignalR and not something that a user should be expected to touch. This is by design.
