### ISSUE TITLE
Looses last progress reports

### ISSUE THREAD

**Issue by dizel3d** [SignalR/SignalR#3803]
I have a hub with asynchronous method that sends some items one by one through `IProgress`. I call this method in a web browser using `jquery.signalR-2.2.1.min.js` API.

### Expected  behavior

All items have been received before the promise completed.

### Actual behavior

Last sent items have not been received, even after the promise completed.

### Steps to reproduce

Create a hub
```cs
public sealed class MyHub : Hub
{
    public Task Fetch(IProgress<dynamic> progress)
    {
        return Task.Factory.StartNew(() =>
        {
            var items = new int[5000].Select((x, i) => i);

            foreach (var item in items)
            {
                progress.Report(item);
            }
        });
    }
}
```
Use it in a web browser:
```js
$.connection.myHub.server.fetch().then(
    () => console.log('done'),
    () => console.log('fail'),
    x => console.log('prog', x)
)
```
Result:
![image](https://cloud.githubusercontent.com/assets/593571/19928907/c66ab4fc-a111-11e6-9b9a-008dcb6c0e6b.png)

**Comment by dizel3d** [comment]
I suggest:
1. **Fix the bug.** Clear a sending progress report queue as soon as a method is completed.
2. **Add a feature.** Add a method `Wait()` to `IProgress` to guarantee all sent progress reports are received by client. I mean this:
```cs
public sealed class MyHub : Hub
{
    public Task Fetch(IProgress<dynamic> progress)
    {
        return Task.Factory.StartNew(() =>
        {
            var items = new int[5000].Select((x, i) => i);

            foreach (var item in items)
            {
                progress.Report(item);
            }

            // HERE! guarantee that all sent progress reports are received by client
            progress.Wait();
        });
    }
}
```

**Comment by IanYates** [comment]
You need to change your perspective.

You're calling to the client from the server.
Separately, you're queueing up some data from the server to be sent to the client, one at a time.

In your mind the `queue` bit is missing because you're doing the server->client comm from within your client->server call.

When you look at the server->client bit as a queue then you can rejig your approach.  I would think it'd be easier to have your client call the server and start this process.  That's a quick call and it's over quickly - this is because you kick off work in a background task and don't await its completion, nor do you return it to the client.  
The server does its progress reports.  At the end it calls to the client to signify finished.  It's this call that the client is waiting for.

Note: you can ask SignalR, from outside of a hub, to give you back an interface through which any arbitrary code can make a call to a client.

**Comment by dizel3d** [comment]
@IanYates, I want a client to process data concurrently with the task progress, not at the end of task. If I understood your advice correctly, you suggested to me sending intermediate results via client method calls. But what if one client has invoked the sever method twice in the same time? How to match received intermediate results with invocations?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
