### ISSUE TITLE
[Feature Request] SignalR.Client: Cloudflare bypass support

### ISSUE THREAD

**Issue by pogarek** [SignalR/SignalR#3844]
Hi
In case that SignalR server is behind Cloudflare , the Client cannot connect.
It would be nice to have bypass functionality, for example based on https://github.com/elcattivo/CloudFlareUtilities . (nuget package is available as well : https://www.nuget.org/packages/CloudFlareUtilities ) 

Thank you.

**Comment by asavis** [comment]
+1
At least it should be possible to install DelegatingHandler to implement something like that.

**Comment by moozzyk** [comment]
You can pass an [IHttpClient](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Http/IHttpClient.cs) implementation when [starting a connection](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L433). Would it be enough to make it work?

**Comment by asavis** [comment]
That might help to pass negotiation step. However next step (connect with Upgrade:websocket) is blocked again by Cloudflare. To resolve that problem two steps required: 1. Pass cookies obtained during negotiation step from Cloudflare.  2.  Use the same User-Agent as during the negotiation step. For 1 the easiest fix is to add CookieContainer = new CookieContainer(); to Microsoft.AspNet.SignalR.Client.Connection(). For 2 I found no easy way because there is no way to set User-Agent to ClientWebSocket (SetRequestHeader does not allow to set User-Agent). I had to re-implement ClientWebSocket  and ClientWebSocketOptions so User-Agent is possible to set.

**Comment by moozzyk** [comment]
ClientWebSocket does not have the API to set the User-Agent header and we will not re-implement ClientWebSocket. I guess you will have to use ServerSentEvents or LongPolling in your case.

**Comment by asavis** [comment]
Or fork SignalR + ClientWebSocket and add required functionality as I already did. Thanks anyway.

**Comment by lnaie** [comment]
thanks for sucking at it! :)

**Comment by asavis** [comment]
@siberianguy The patch https://jpst.it/18sKJ for Microsoft.AspNet.SignalR https://github.com/SignalR/SignalR (I am using Microsoft.AspNet.SignalR.Client45 from there as you see). You will find there a new file ClientWebSocket2 that is taken manly from https://stackoverflow.com/questions/22635663/setting-user-agent-http-header-in-clientwebsocket.
