### ISSUE TITLE
"类型“System.Net.Http.WebRequestHandler”违反了继承安全性规则。派生类型必须与基类型的安全可访问性匹配或者比基类型的安全可访问性低。"

### ISSUE THREAD

**Issue by judypol** [SignalR/SignalR#3859]
I used the signalr.client in asp.net, and the dotnet framework4.6.1,the signalr.client is 2.2.1
the error is details:
"   在 Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.CreateHandler()
   在 Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.Initialize(IConnection connection)
   在 Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetNegotiationResponse(IHttpClient httpClient, IConnection connection, String connectionData)
   在 Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.GetNegotiateResponse(IConnection connection, String connectionData)
   在 Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.Negotiate(IConnection connection, String connectionData)
   在 Microsoft.AspNet.SignalR.Client.Connection.Negotiate(IClientTransport transport)
   在 Microsoft.AspNet.SignalR.Client.Connection.Start(IClientTransport transport)
   在 Microsoft.AspNet.SignalR.Client.Connection.Start()

**Comment by moozzyk** [comment]
Please provide a repro as the information provided is not sufficient to figure out what's causing this error.

**Comment by judypol** [comment]
the code is：
var hubConnection = new HubConnection(ConfigurationManager.AppSettings["signalrUrl"]);
                IHubProxy proxy = hubConnection.CreateHubProxy("MyHubs");
                hubConnection.Start().GetAwaiter().GetResult();

                proxy.Invoke("RegisterStudent",stu).GetAwaiter().GetResult();

**Comment by moozzyk** [comment]
What kind of project is that? Did you install SignalR into your project using NuGet? I don't think that the issue here is the code itself (although you should `await` async calls instead of using `.Result`/`.Wait` which blocks the thread and may lead to deadlocks) but that you have mixed references. You mention you refer System.Net.Http 4.1.0 but if you look at dependencies here: https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/ none of the client versions depend on this.
