### ISSUE TITLE
Signalr vs Websocket-sharp

### ISSUE THREAD

**Issue by deniskrop** [SignalR/SignalR#3866]
I wrote my app's server in C++ with [µWS](https://github.com/uWebSockets/uWebSockets), and have already written a Javascript client for it. Now I'm writing a C# client for it with Mono, and am currently using the [websocket-sharp](https://github.com/sta/websocket-sharp) library when I came across other libraries such as Signalr, Alchemy-Websockets, and Fleck.

Has anyone done any benchmarks on what the fastest C# library compatible with Mono for websockets is, or is there one generally recommended?

**Comment by moozzyk** [comment]
SignalR is not a webSocket library. It does use webSockets for one of its transports but having/using webSockets is not required. I don't know what capabilities other libraries have - when comparing/benchmarking make sure you are comparing apples to apples.

**Comment by reddyBell** [comment]
Is it possible to configure the server-side implementation of WebSockets that SignalR is using ? (for example by implementing an interface) 

Since as far as I can see, Mono has not implemented WebSockets yet. This would also us to plug third-party Websockets libraries to benefit from WebSockets with SignalR on a Mono stack

**Comment by nkosi23** [comment]
My mistake, apparently is has been implemented :
https://github.com/mono/mono/blob/master/mcs/class/referencesource/System/net/System/Net/WebSockets/WebSocket.cs
