### ISSUE TITLE
Issue with IPv6 and IE/Edge

### ISSUE THREAD

**Issue by gabriellebourdages** [SignalR/SignalR#3875]
We are currently experiencing problems with SignalR when using IPv6 and Internet Explorer 11/Microsoft Edge. Our version of SignalR is 2.2.0.

What happens is that the WebSocket connection fails because signal R tries to connect using an IPv6 address in the wrong format (missing [brackets]). We get the following error in the logs 

> webSockets transport threw 'SyntaxError' when attempting to start.

The "negotiate" and "abort" calls do use the correct format, but the WebSocket calls don't. 

It is working fine using Chrome and Firefox and the connection.url does have the brackets, so I don't know at which point they get removed.

![image](https://cloud.githubusercontent.com/assets/6413460/23187477/eb67e326-f858-11e6-9414-a1d0ac5242c7.png)

I'm not sure if anyone else ever encountered that problem and if it is a bug or an environment problem, but if anyone has some kind of input on the situation it would be greatly appreciated!

**Comment by moozzyk** [comment]
Did you use the IP Address to load the page that contained SignalR? Because SignalR relies on the browser [to get the host name](https://github.com/SignalR/SignalR/blob/5c609d17cd556d9c1b8c3eda0b4e37f00a4fc535/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js#L436). A possible workaround can be to provide the full url when creating the connection.

**Comment by gabriellebourdages** [comment]
The page is loaded using the Ipv6 address in between brackets and when we setup the connection we specify `connection.url = https://[xxxx:xxxx:x:xxx:xxxx:xxxx:xxxx:xxxx]/applicationPath/signalr` . From what I see when I inspect the `window.document.location` inside IE or Edge, everything seems normal (the address is always formatted properly). Maybe there is some other setting beside the `connection.url` that I can setup when we start Signal R.

**Comment by moozzyk** [comment]
You sanitized links used to attempt to start websockets and longpolling transports so I am not sure what was passed. How did they look - did they have square brackets or they didn't? (Looking at [this](https://social.msdn.microsoft.com/Forums/windowshardware/en-US/5f984afc-8ec0-4dc0-b723-47fdd70b9a6b/websockets-in-ie-and-edge-with-ipv6?forum=iewebdevelopment) I think the websocket one was in square brackets but am not sure about longpolling). Another question - what does _the address is always formatted properly_ mean? Is it in square brackets or not?

A separate question/workaround - why do you want to use the ip address to connect instead of the host name have dns do its job?

**Comment by gabriellebourdages** [comment]
Sorry if I was unclear. When I say formatted properly, it means that the square brackets are there, and in my sanitation, I left the square brackets when there were any (so any blacked-out string that is not wrapped in brackets, it means there weren't brackets at all).

And for your separate question: we're just trying to make sure that our application works no matter which URL the users input in their browser.  Most of them will probably use the DNS and there won't be a problem, but if they ever want to use an IPv6 address instead (it's in a self-host setup so they might use private addresses and such), they will run into this problem where signalR can't connect.

I'm trying a workaround where I use the relative URL instead and just specify "/applicationPath/signalr" as the url, but I still get a 'SyntaxError'. SignalR ends up using foreverFrame transport instead and manages to connect though.

**Comment by moozzyk** [comment]
[Looks like](http://stackoverflow.com/questions/15157910/ipv6-address-giveing-syntax-error-in-internet-explorer-10-websocket) for webSockets you would have to use _Literal IPv6 addresses in UNC path names_ when using IE or Edge. One thing I don't quite understand is why the poll request fails - negotiate worked fine and we are sending requests the same way.

**Comment by gabriellebourdages** [comment]
Yeah I think this is the best workaround! It just seems like the way the address is parsed ( `window.document.createElement("a")` ) does not work exactly the same in IE/Edge as it does with the other browsers. But even if it did extract the host correctly (with the square brackets I mean), we would still run into the problem that IPv6 with brackets formatting and websockets don't work in microsoft browsers.

Anyways, thanks a lot for your help!

**Comment by moozzyk** [comment]
Honestly, I don't know how far you can get with using IPs instead of host names. For instance SSL certifcates are typically bound to host names/domains and not IP addresses.  Also, when using names nothing needs to be done on the user side in case the host IP address changes. 

I am closing this issue for now since I don't expect us to make changes to accommodate this browser specific behavior. We can revisit this if this becomes a more common request.

**Comment by ogauthier** [comment]
We have run into the same issue, as we need to support IPv6 browsing and then SignalR isn't working in IE and Edge.

**Comment by moozzyk** [comment]
@ogauthier  - Why do you use IPv6 addresses instead of names?
