### ISSUE TITLE
Bug with GetTypesSafe(Assembly a) in ReflectedHubDescriptorProvider

### ISSUE THREAD

**Issue by bklooste** [SignalR/SignalR#3963]
### Expected  behavior
No thrown exception only trace

### Actual behavior
 System.NotSupportedException thrown on a.Location

            try
            {
                return a.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                _trace.TraceWarning("Some of the classes from assembly \"{0}\" could Not be loaded when searching for Hubs. [{1}]\r\n" +
                                    "Original exception type: {2}\r\n" +
                                    "Original exception message: {3}\r\n",
                                    a.FullName,
                                    a.Location,
                                    ex.GetType().Name,
                                    ex.Message);
### Steps to reproduce
In a program that does some xml serialization call this after the serialization..

It is also likely that people who got this error for debugging for the same reason, 

Workaround .. In some cases you can call it early before the cache is built this is why most people dont see the error.

I have created a trivial pull https://github.com/SignalR/SignalR/pull/3964

**Comment by moozzyk** [comment]
We should refine https://github.com/SignalR/SignalR/pull/3368.

**Comment by moozzyk** [comment]
#3657

**Comment by IGx89** [comment]
A production app of mine just ran into this as well, immediately after a daily app pool recycle. Recycling the app pool again resolved it.

Since this has apparently been a known issue since 2014 I'm not holding out hope it'll be fixed soon, however I'm curious if the .NET Core version of SignalR is affected or not by this issue? I would guess yes, due to how major of refactor it is, but if not we'd definitely want to make sure this issue is on their radar as well.

**Comment by moozzyk** [comment]
I put it to the vNext milestone so that it is considered in the next servicing release.

**Comment by liammycroft** [comment]
Will this need to be re-raised based on the techical bankruptcy decalred in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/

**Comment by anurse** [comment]
Normally, yes, it would need to be pinged and re-opened (as you've noticed we haven't done the closing yet)

However, this should already be resolved for 2.4.0, since I encountered it in some of our tests. See https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Core/Hubs/Lookup/ReflectedHubDescriptorProvider.cs#L113 . I'm going to close this as fixed in 2.4.0. There will be a preview release (which will be announced on the blog you referenced above) soon and if the issue still occurs in that build, feel free to ping this issue and we'll continue investigating!
