### ISSUE TITLE
Can not step into SignalR.Client code

### ISSUE THREAD

**Issue by fabercs** [SignalR/SignalR#3976]
### Expected  behavior
I would like to debug connection.Stop() behaviour in my application, so I applied the steps as indicated [here](http://www.symbolsource.org/Public/Wiki/Using)
### Actual behavior
I can not debug (step into) the code. While debugging, under the modules I see that "Can not find or open PDB file"
### Steps to reproduce
Visual studio 2017 community edition
.Net (4.5) client
Signalr version 2.2.2

**Comment by moozzyk** [comment]
I don't think we publish symbols anywhere. I also think that even with symbols the code would be hard to debug since it is optimized so you likely won't see most variables and the debugger may jump all over the place when stepping through the code. I suggest you clone the code and build a debug version of the dll you want to debug and use it in your project. 

Caveats:
- The solution was not converted to VS 2017 - this is being tracked here: https://github.com/SignalR/SignalR/issues/3938 and will be done before the next servicing release
- There is a ton of requirements (like Windows SDK etc.) you probably did not install and don't want to install

How to proceed:
- Clone the repo and switch to the dev branch (it is in sync with release at the moment)
- Open .\Microsoft.AspNet.SignalR.sln in VS 2017
- You will get warnings about incompatible projects and missing requirements - ignore these
- You will be prompted to update projects/solution - do this. You will likely get errors - again ignore these
- You will end up with a solution where some projects could not be loaded - this is fine because you will not need these projects (Silverlight, WindowsStore etc.)
- Now just right click and build the project you need - you will get a debug version of the dll along with matching symbols you could use to debug. 

An alternative is to clone and run build.cmd from a VS command prompt. It will fail on missing dependencies so you would have to install them until you have all you need. When build.cmd passes it will create all dlls and symbols (note build.cmd runs tests which have another set of requirements like IIS Management Console). You may want to run `build.cmd /t:BuildPackages` which builds the dlls and creates NuGet packages but does not run tests.

**Comment by fabercs** [comment]
I would like to debug only Client project, luckily it doesn't require any dependencies. I downloaded it, built it and smoothly debugged. Thanks for guidance.
