### ISSUE TITLE
Environment is reset on messages with serverSentEvents transport

### ISSUE THREAD

**Issue by sondreb** [SignalR/SignalR#3991]
### Expected  behavior
Values set on Environment["key"] can be set in one call and read in another call. This can be used to keep some state on the server for the active connection.

### Actual behavior
When clients connect using serverSentEvents, any custom value (e.g. Hub.Context.Request.Environment["server.User"]) set previously on the connection is reset (null).

With WebSocket transport connections, this works as expected (values written in first call, is available in second call).

### Steps to reproduce
Force the connection to use serverSentEvents on the client:

```
start({ transport: ['serverSentEvents'] })
```

Perform some calls to the server and set environment variables:

```
context.Request.Environment["server.User"]
```

Perform another call and attempt to read the value back. The result will be null.

SignalR is hosted with OWIN, running on a local .exe with web app running from localhost. Shouldn't be any firewall issues. SignalR is hosted on separate address than the web app, and communication is done over HTTPS/WSS.

Is this a known and expected behavior or a bug? Is there another way of keeping state on the server which can survive multiple calls from clients connected with serverSentEvents?

**Comment by sondreb** [comment]
The same applies to longPolling transport, was unable to get foreverFrame working at all.

**Comment by moozzyk** [comment]
`context.Request.Environment` is a per-request environment. In case of serverSentEvents and longPolling transports each message sent from the client is creating a separate HTTP request so if you store anything for one request it won't be there for a different request. WebSockets is a persistent transport and you are dealing with the same request as long as the webSocket is connected so it appears as if the data was persisted. You will lose your value though as soon as there is a reconnect because the original request will be closed.
