### ISSUE TITLE
SignalR only Working when both person is on Different type of browser

### ISSUE THREAD

**Issue by symon01107** [SignalR/SignalR#4011]
I am having some bad time here. I have a chat application. Our async functionality using signalR only works when both person are in different types of browser. I need some expert advice here. I can show code if required. Please let me know if anyone face same issue. I tried to log signalr in browser. Still logs only show when both person in different type browser ( But I can see connection started successful response in XHR tab). No log when both are in different type browser from different machine. We are using azure here.

**Comment by moozzyk** [comment]
SignalR works just fine across different browsers. In fact, the client does not know what browser (if any - because the other client can use a C# client, a C++ client etc.) other connections are using, so it is unlikely a SignalR issue. I would recommend asking a question on stackoverflow and provide more details.
