### ISSUE TITLE
IProgress functionality does not work with .NET client if Hub's JsonSerializer.TypeNameHandling is set to Auto

### ISSUE THREAD

**Issue by jcwallace03** [SignalR/SignalR#4014]
### Expected  behavior

Client's Progress Callback method gets invoked when server Hub calls IProgress<T>.Report

### Actual behavior

Callback is never invoked.

Exception in client trace: 

Newtonsoft.Json.JsonSerializationException: Could not load assembly 'Microsoft.AspNet.SignalR.Core'.

### Steps to reproduce

When registering the JsonSerializer in the DependnecyResolver, set the TypeNameHandling value to TypeNameHandling.Auto.

Setting value to None results in expected functionality, but polymorphic serialization no longer works (i.e. cannot send derived types over wire when cast as base class).

**Comment by jcwallace03** [comment]
Is there another way to pass derived types declared as the base class or interface from the hub to clients without using TypeNameHandling?

Would implementing my own JsonConverter do the trick?

**Comment by nightmare233** [comment]
##-Please type your reply above this line-##
 
 Hi {!Ticket.Name} , 
  
 Thank you for contacting us! 
  
 We have received your query as below: 
  
 Is there another way to pass derived types declared as the base class or interface from the hub to clients without using TypeNameHandling?

Would implementing my own JsonConverter do the trick?

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/SignalR/SignalR/issues/4014#issuecomment-364604738 
  
 To help track your query, we have generated a Comm100 Ticket Id. Your Comm100 ticket Id is S34008-T117. Please include this ticket number in all your communications with us. 
  
 We will resolve your query and contact you as soon as possible. 
  
 If you have any other question, please feel free to contact us. 
  
 Sincerely yours, 
  
 



CNaqH_OgpPM_harCu

**Comment by jcwallace03** [comment]
I was able to work around this using the following solution: https://stackoverflow.com/questions/32314638/signalr-typenamehandling

Thanks,

John

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
