### ISSUE TITLE
Calling for Hub method from the hub without client Invocation 

### ISSUE THREAD

**Issue by AlameerAshraf** [SignalR/SignalR#4034]
I' m asking about the ability of SignalR Events to invoke a Hub method , from the Hub it self and Broadcast it to the Connected Clients as if invoking a Clint method 
`Clients.All.addContosoChatMessageToPage(name, message);`
in which the **addContosoChatMessageToPage**  is a Hub method ?

**Comment by AlameerAshraf** [comment]
This can be accomplished by Instainted an object from the hub itself and invoke the target function.

`// Get the context of the Pusher hub
IHubContext hubContext = GlobalHost.ConnectionManager.GetHubContext<Pusher>();

// Notify clients in the group
hubContext.Clients.Group(group).GetData(data);`

**Comment by MichaelVincentHubbard** [comment]
Well if you're talking about I think it computed 10 or twelve around ten to the forth I wrote the script so, I mean do you mean count to 100 million haha.
What do you mean.
Maybe just estimating what are you talking about? 
Michael


Sent from my Samsung Galaxy , an AT&T LTE smartphone
-------- Original message --------From: Alameer Ashraf Hassan <notifications@github.com> Date: 11/25/17  3:04 PM  (GMT-08:00) To: SignalR/SignalR <SignalR@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [SignalR/SignalR] Calling for Hub method from the hub without
  client Invocation (#4034) 
Closed #4034.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SignalR/SignalR","title":"SignalR/SignalR","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SignalR/SignalR"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #4034."}],"action":{"name":"View Issue","url":"https://github.com/SignalR/SignalR/issues/4034#event-1357975802"}}}
