### ISSUE TITLE
Version 2.2.3 has dll's with lower file version

### ISSUE THREAD

**Issue by smoeller-liveid** [SignalR/SignalR#4090]
Hello,
I just updated from 2.2.2 to 2.2.3 via nuget. But while version 2.2.2 dll's have a file version 2.2.60504.1171, the new version 2.2.3 uses a file version 2.2.10306.1417.

This will break all MSI installs, because the limited MSI logic during an update first deletes the "old" version ("2.2.60504.1171"), and then refuses to install the "new" version ("2.2.10306.1417") because it is older than the (no longer) existing file.

So, unless someone fixes the MSI installer logic, it is mandatory that versions are strictly increasing.
The affected files are "Microsoft.AspNet.SignalR.Core.dll" and "Microsoft.AspNet.SignalR.SystemWeb.dll".

Sebastian

**Comment by anurse** [comment]
The change was done because we were running out of file version numbers due to the way we generate them, but you're right, that would break MSI installation. We'll have to consider how best to fix this. Do you require the fix in 2.2.3? If not, I suggest downgrading to 2.2.2, as there is only a single fix in 2.2.3: https://github.com/SignalR/SignalR/issues/4036

**Comment by smoeller-liveid** [comment]
I already downgraded, think this is fine for me for some time.
Thanks

Outlook für iOS<https://aka.ms/o0ukef> beziehen
_____________________________

**Comment by vvvlad** [comment]
are there any plans to fix this, or is there any way you can suggest to overcome this issue?

**Comment by anurse** [comment]
We're fixing this by releasing our next patch as `2.3.0`, it'll still just be a patch, we aren't planning any new features, but it should resolve the file version issues.

**Comment by anurse** [comment]
The next patch release (`2.3.0`) is out and should have this fix.
