### ISSUE TITLE
Handle MessageBus exceptions during initial connection

### ISSUE THREAD

**Issue by lupine86** [SignalR/SignalR#4096]
### Expected  behavior
When connecting to signalR from a Web javascript client if the MessageBus is offline (and throwing exceptions) the error should make its way back to the client so it can be handled.  If the MessageBus is offline it isn't desired to try all the transports and then abort when a connection was never fully initialized.

### Actual behavior
If the MessageBus is "offline" signalR client timesout waiting for an initialization message.  It then tries all the fallback transports which fail as well since the MessageBus is offline.  Then it tries to Abort (which also fails since the MessageBus is offline)

### Steps to reproduce
1. Register a custom MessageBus
2. override Publish(Message message) and throw an arbitrary exception (e.g. NotImplementedException)
3. Try to connect to from Web client

**Comment by anurse** [comment]
How would you want to react to this on the client? If the message bus fails, the server is down. Are you just looking for things to fail faster rather than timing out?

**Comment by lupine86** [comment]
Not necessarily faster, but fail in such a way that the client doesn't try other transports.  
What I see frequently is that there is a timeout on the message bus and the client falls back to trying another transport and then sticks to that transport.  Trying a different transport isn't why the connection was successful, the Message Bus just didn't timeout the next time around.

**Comment by anurse** [comment]
Let me clarify what's going on in your scenario:

* Your custom message bus is occasionally timing out
* When it times out, an exception is thrown
* The client is reacting to this exception by trying a new transport

The problem here is that the client doesn't really know **why** the connection failed (by design), so all it knows to do is try a different transport.

**Comment by lupine86** [comment]
That is pretty close - I would elaborate a little to put it like this:
- The client is successfully connecting to server with a Web Socket connection
- Custom message bus (build on Azure Service Bus) is occasionally timing out while publishing the initialization message (Some times it doesn't time out, but takes longer than client is willing to wait (default 5 seconds) - see [transportTimeout](https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.common.js#L105).  Network latency can also play a role in hitting this timeout)
- The client transport times out 
- The client closes the Websocket (that was successfully opened)
- The client tries a new transport

The client knows the transport failed (even though the connection was successful) so it tries another transport instead of trying again using same transport (or maybe it should give up?)  I guess the question is, should the client really try another transport if the connection using the transport was successful but the initialization of the transport times out?

**Comment by anurse** [comment]
> Custom message bus (build on Azure Service Bus)

I'm curious why you have a custom message bus based on Azure Service Bus. We do have an [official implementation](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-windows-azure-service-bus) that uses Service Bus.

> I guess the question is, should the client really try another transport if the connection using the transport was successful but the initialization of the transport times out

The problem is this is exactly how some WebSocket failures can manifest. The connection will appear to succeed, because the proxy sent the necessary upgrade headers (and possibly even some frames). However, at some point, because the proxy is unaware of how WebSockets works, it will think the request is just taking too long and terminate the underlying TCP connection. So we don't really have a way on the client to know that the transport failed because the server connection simply crashed or if some proxy is interfering and WebSockets will simply never work.

**Comment by lupine86** [comment]
> I'm curious why you have a custom message bus based on Azure Service Bus. We do have an official implementation that uses Service Bus.
Our implementation inherits from `ScaleoutMessageBus` to implement additional functionality beyond what the official implementation provides.  The custom Message Bus is used to support two different backplanes to allow the product to run on prem or hosted.

Anyway - Thank you for the response which makes a lot of sense.

**Comment by anurse** [comment]
Gotcha. Just wanted to understand if there was something our backplane wasn't supporting, but it does sound like this is specific to your scenario. Thanks!
