### ISSUE TITLE
How to get rid of "System.InvalidOperationException" The requested performance counter is not a customer counter, it has to be initialized as ReadOnly

### ISSUE THREAD

**Issue by davisford** [SignalR/SignalR#4113]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior

I whould be able to execute `app.MapSignalR('/api/signalr', hubConfiguration)` without it throwing an Exception.

### Actual behavior
It always throws this exception on startup

### Steps to reproduce

Look, I know this has been asked here https://github.com/SignalR/SignalR/issues/1875, but the answer is unsatisfactory: 

> The first exception (the title of the bug) should be first chance and ignored.

I want to know how to get rid of this.  I don't want to disable `System.InvalidOperationException` in my debugger exception settings, b/c it is kind of a big deal, but every single time I debug my app, I have to wait for this and then continue.  

Can someone please point me to some docs that can explain: 

1. What is the name of the perf counter it can't load?
2. How can I load it or fake it (I don't care about using the counters at this time)?
3. Is there any other workaround?

**Comment by MagicAndre1981** [comment]
Download the[ matching version for your used SignalR client version](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Utils/), run **SignalR.exe ipc** to [install the performance counter](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-performance#using-signalr-performance-counters)

**Comment by anurse** [comment]
To be clear, this exception is not crashing your application, it's breaking into the debugger because you have explicitly configured the debugger [to break on first-chance InvalidOperationExceptions](https://blogs.msdn.microsoft.com/devops/2015/01/07/understanding-exceptions-while-debugging-with-visual-studio/)? Can I ask why you need to break on first-chance InvalidOperationExceptions instead of the default configuration which breaks the debugger only on **uncaught** exceptions? In general, breaking on first-chance exceptions (or "break when thrown") causes a lot of this kind of behavior as there are a few places in the framework where exceptions are unavoidable.

The only way we could really "fix" this is by giving you a setting somewhere to completely disable performance counters. Because of the way the PerformanceCounter APIs work though, there's no way to prevent this _first-chance_ exception without completely disabling performance counters, which is why SignalR catches this exception so that it doesn't crash your application. We can consider adding that setting, but it would only be one of many possible places a first-chance InvalidOperationException could be thrown
