### ISSUE TITLE
How to get Signal R active connections in azure scale out / behind load balancer

### ISSUE THREAD

**Issue by kamranbashir** [SignalR/SignalR#4115]
1). When you have a single instance, you can do below to get active clients /connection list
var transportHeartbeat = GlobalHost.DependencyResolver.Resolve<ITransportHeartbeat>();
 var activeConnections = transportHeartbeat.GetConnections().Where(c => c.IsAlive).Select(k => k.ConnectionId); 

2). But when you have azure scale out for your Signal R hub , then you have multiple instance of the app behind load balancer.
I am trying to update connection status in redis cache on following events on hub
•	OnConnected
•	OnDisconnected
•	OnReconnected
Some time when a client leaves and disconnect event happen after 30 secs, but with in time frame the client re-connect, we are unable to get correct status of a client is connected or not.

Is there any proper way to solve the problem? Has some on has done before?
for getting accurate connected clients lists across multiple instances

Thanks in advance

**Comment by anurse** [comment]
It's not generally possible to get a perfectly accurate connection count when multiple servers are involved because of networking delays and reconnection windows. What's the main goal you are trying to achieve? Why do you need an "accurate" connection count and what kind of accuracy are you looking for?

**Comment by ajbeaven** [comment]
I'm experiencing this issue too.

Our application is a chat system - we need to remove users that have disconnected from the online user list. In cases where the user closes the browser, OnDisconnect is fired correctly, however when a user's internet is cut off, it is not fired so the online list is incorrect.

We're using the 'user presence' approach in the project linked to [here](https://stackoverflow.com/questions/21066657/signalr-ondisconnected-a-reliable-way-to-handle-user-is-online-for-chatroom) by @davidfowl.

It doesn't need to be "up to the second" accurate, but I would hope to be able to determine users that needed to be timed out had they been disconnected for more than a minute. Is the only reliable way to ping the server from each client and have a threshold?

**Comment by ajbeaven** [comment]
Would the issues here be resolved by setting up IIS ping/pong as suggested in #3476?

**Comment by anurse** [comment]
> Is the only reliable way to ping the server from each client and have a threshold?

That's probably your best option.

> Would the issues here be resolved by setting up IIS ping/pong as suggested in #3476?

No, those ping/pongs are the protocol-level ping/pong messages used in WebSockets. The .NET WebSockets APIs don't expose them so unfortunately you'll have to have your own ping/pong messages. However, the WebSocket infrastructure only actually sends it's ping/pong frames if the connection is idle so you aren't likely to add extra chattiness by putting your own pings (because the built-in ones won't be triggered because your pings are keeping the connection from going idle).

**Comment by ajbeaven** [comment]
Awesome, have implemented and it seems to work fine. Thanks heaps!
