### ISSUE TITLE
All clients disconnected at the same time?

### ISSUE THREAD

**Issue by mhellsten** [SignalR/SignalR#4118]
We are seeing huge spikes of traffic on our SignalR backplane, because it appears that all of our clients (~700 concurrent) disconnect simultaneously a few times a day. 

Often times, I see an exception like this in the EventLog around the same time, but I don't see any signs that it crashes the worker process:
```
Exception information: 
    Exception type: HttpException 
    Exception message: The remote host closed the connection. The error code is 0x80070057.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.WriteFromStream(Byte[] data, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Hosting.ResponseExtensions.End(IResponse response, String data)
   at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(HostContext context)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
```

There's not much going on in our event handlers. The task management and error handling here is bad, but it doesn't seem to be the cause of the issue:
```
        public override Task OnDisconnected(bool stopCalled)
        {
            try
            {
                Task.Factory.StartNew(() => { SignalRSqlCommands.DeleteConnectionFromOpenConnectionsRepo(Context.ConnectionId); });
                return base.OnDisconnected(stopCalled);
            }
            catch (Exception e) { LogInfo(e.ToString()); return null; }
        }
```

Any thoughts as to what could be causing this?

Thanks!

**Comment by anurse** [comment]
What kind of server are you running? Is this a Virtual Machine, Physical Machine or Azure App Service?

**Comment by mhellsten** [comment]
@anurse: Thanks for taking a look! It's running on a several Windows server / ASP.NET clusters with about three nodes each, all VMWare VMs in a private data center.

**Comment by anurse** [comment]
Hrm, OK. I'm not aware of anything obvious that should be causing mass disconnects like this. Usually if that happens in this way it's due to some intermediate proxy terminating the connection. Would you be able to collect server traces (and ideally client traces from a client that is disconnecting) using the guidance posted here? https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing

**Comment by mhellsten** [comment]
We have F5 load balancers in front of the farms. I don't have any indication that other traffic is affected. I have logging for all the events that traverse the backplane, but getting the clients involved could take some time to pull off, due to work backlog. Also it's tricky to predict when it'll happen or I'd use Wireshark.

**Comment by anurse** [comment]
I what transport the connections are using. WebSockets tend to be the most likely to cause these kinds of mass disconnects since they are a single long-running connection, whereas if a Long Polling request terminates, the client simply issues another.

Perhaps the load balancer might have information about if/why it is terminating a connection? Assuming you aren't seeing any other errors on the client or server (aside from the remote host closing the connection), it is likely some intermediary is terminating the connection.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by amitgg1612** [comment]
Hi, we are facing the same issue. All the clients are disconnecting every 29 hours. Could this be helped please?
