### ISSUE TITLE
signalr.exe ghp crashes if project references NewTonSoft

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4152]
If a web-project references NewtonSoft.Json then signalr.exe fails to generate proxy JS.

### Expected  behavior

js-file

### Actual behavior

Crash

``Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

Temp workaround - manually creating a `signalr.exe.config` file and setting assembly redirect in the file like described [here](https://stackoverflow.com/a/33400441/56621). But this sucks cause /packages folder is usually not tracked by git, so it's a PITA to fix this for everyone in a big team.

FIX THIS PLEASE

**Comment by anurse** [comment]
This one is difficult to fix because of how the Utils package works. We load your application assemblies up into the `signalr.exe` process, which means that any binding redirects your app uses have to be moved over to a `signalr.exe.config` file (and we can't just add them ourselves because it's too late, the process is already loaded). We may be able to make something work here with the AssemblyResolve evnet though, I'll take a look and see what I can find.
