### ISSUE TITLE
Unhandled: System.Runtime.InteropServices.SEHException - External component has thrown an exception.

### ISSUE THREAD

**Issue by cblaze22** [SignalR/SignalR#4154]
I am using the latest version of Signalr for .NET Framework.  Everything seems to be working well, however we are now getting this worker process crash with the error below.  This has never happened before and only started happening after releasing Signalr and doing real time updates.  We use LeanSentry but it doesnt tell us much about this error.  Does Signalr have issues around this error and if so what can I show you to figure out why this is happening?  

It has happened once per day but that is unacceptable for the type of site we have and traffic when the entire site needs to recompile.

`Unhandled: System.Runtime.InteropServices.SEHException - External component has thrown an exception.`

**Comment by anurse** [comment]
I'm not aware of any reports of that exception in the past. It usually occurs when there are errors loading native code (which SignalR does not do). Sometimes other things can cause it though. You can try looking at the [ErrorCode](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.externalexception.errorcode.aspx) property on the exception itself to see if that provides any more information.

**Comment by cblaze22** [comment]
I dont know about that?

https://github.com/aspnet/SignalR/issues/1611

**Comment by anurse** [comment]
The issue you linked is for ASP.NET **Core** so it's not necessarily directly related. Also it's occurring on a client but my understanding is that you're seeing it on a server. I was referring to reports for ASP.NET SignalR.

You're right that there may be a common denominator here though since it seems to occur in ASP.NET Core when using WebSockets. Are you using the WebSockets transport from your client (it's likely you are if you have the default configuration). (cc @stephentoub just in case he's seen SEHExceptions coming from the Windows _native_ WebSocket APIs in the past)

Memory shouldn't be causing this issue. As the docs say: "STATUS_NO_MEMORY exceptions are automatically mapped to the OutOfMemoryException class.", so you'd be getting an `OutOfMemoryException` if you were running out of memory. This is indicating some other native exception bubbling up to .NET code.

Have you been able to get a stack trace or any other information from the exception? Just having the message doesn't really get us much to work from unfortunately. If it's a terminal exception (crashing the process) there should be something in the Windows Event Log with some more detail. Or if you're able to have a debugger attached that might provide more context.

**Comment by anurse** [comment]
You could try adding a handler to [`AppDomain.UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=netframework-4.5.1) and try collecting as much data from that exception as you can there, to ensure that next time this happens you've got some more context.

If the exception isn't likely to occur again for a while we might be stuck for a bit. I take it this isn't something you can reproduce reliably?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
