### ISSUE TITLE
Disconnect issue

### ISSUE THREAD

**Issue by mehranzand** [SignalR/SignalR#4161]
Hi,

We store all connection ids in DB when connecting and discounting server events raised. 
After a working day some connection id remained in DB but there is no any real connection the web site! I think sometime disconnect event not fired properly. Any idea?

Thanks in Advance

**Comment by anurse** [comment]
There are scenarios where the disconnect event can fail to fire, especially in scale-out scenarios. In general, when there are multiple servers in play it is very difficult to accurately measure the number of connections, since connections can migrate between servers.

The general recommendation here is that if you want to know when a connection appears to be disconnected, you use a timeout value and if you haven't received a hub message from a client within that timeout, consider the client disconnected. What are you using these connections IDs for? In general, it's recommended that you use SignalR Groups to track collections of connections.

**Comment by mehranzand** [comment]
Thank you, We don't scale-out the server yet, We are using the connection ids for chat application but we don't use SignalR Groups, ids directly stored in DB and remove when disconnect event raised.

**Comment by anurse** [comment]
As I mentioned, the `OnDisconnectedAsync` event is not guaranteed to fire for every connection, it's not a reliable measure of disconnected clients since it can miss clients that disappear unexpectedly. If you want to reliably detect disconnected connections you'll need to monitor the connections yourself for inactivity and remove them after some time interval.

**Comment by mehranzand** [comment]
"If you want to reliably detect disconnected connections you'll need to monitor the connections yourself for inactivity and remove them after some time interval."

How to?

**Comment by anurse** [comment]
You can retrieve the `ITransportHeartbeat` service from the dependency resolver (using `GlobalHost.DependencyResolver.Resolve<ITransportHeartbeat>()`) and poll `GetConnections` in a background thread to get the list of active connections. There are `IsAlive` and `IsTimedOut` properties on the `ITrackingConnection` objects you get from `GetConnections` that can give you more information about the status of connections.

Having said that, reliability is always going to be a bit of a problem here. There are often going to be disconnected connections in the database. What are you using the connection IDs in the database for? Can you provide more detail on your scenario?

**Comment by mehranzand** [comment]
> Why are groups not sufficient for your scenario?
Many tables relations to connections table on database, 
Groups store connection on dictionary on the memory, it's not good for our scenario.
So, I decide to develop a agent service to check real connection and apply to connections table.

Thank you
