### ISSUE TITLE
[SignalR Service Support] Clients should stop reconnecting when received 404 from /reconnect request

### ISSUE THREAD

**Issue by vicancy** [SignalR/SignalR#4191]
It is possible that Service side receives a `CloseMessage` and proactively completes the ApplicationTask. However the client keeps reconnecting. When /reconnect responses with 400 BadRequest, or 404 NotFound, it sounds more natural not reconnect at all.

**Comment by vicancy** [comment]
The same for 204 NoContent

**Comment by anurse** [comment]
One option would be to accept the socket/eventsource/etc. (simulating a "successful" connection) and then immediately send `{ "E": "error message" }` to the client and close the socket/eventsource/etc. from the server. That message should cause the client to consider the connection broken and make no attempt to reconnect it.

**Comment by anurse** [comment]
I don't think there is a non-breaking way to do this in 2.4.0. The workaround I suggested above ("accepting" the connection but immediately sending an `{ "E": "..." }` message back and then closing it) should give the Service the ability to stop reconnections since the client will **not** reconnect over that error.

**Comment by vicancy** [comment]
So with `204` what will 2.4.0 client do for SSE and WS? Current Azure Service might return 204 in some fallback cases with Application side completes.

**Comment by anurse** [comment]
We can't detect the difference between status codes when an SSE/WS connection reconnects, so SignalR will continue attempting to reconnect. This is a browser limitation, as I mentioned above, since both the `WebSocket` and `EventSource` APIs do not provide details on the status code returned when a connection fails.
