### ISSUE TITLE
Consider dropping the jQuery direct dependency in the JS package metadata

### ISSUE THREAD

**Issue by anurse** [SignalR/SignalR#4216]
We should consider just droping the jQuery dependency in the JS nuspec altogether. It's way out of date and we don't want to be in the business of having to update it all the time. Users can easily bring in their own version of jQuery.

We **would still require jQuery** we just wouldn't specify it as a dependency in the package. The experience may be unpleasant here, so we need to consider this carefully. If we don't drop it, we should consider updating to 3.0 since we currently depend on 1.6 which is way obsolete. The problem is this would force everyone who updates to 2.4 to update their jQuery, which is also a crappy experience :)

**Comment by Lakritzator** [comment]
I am so happy that you guys are working on 2.4!! I hope to be moving to SignalR for ASP.NET Core some time in the near future, but I need dotnet core 3.0 for it (and self hosting) so this is currently not an option.

I second the idea to remove a dependency which is out of date, but make sure it's clearly documented in the release notes and documentation. I would expect information on which JQuery versions can be used, and which ones are advised.

Are there any known issues with different JQuery versions? I couldn't find any information on compatibility with other versions. Up to now, I have been very hesitant to update, meaning I don't do it frequently, as testing changes in the JavaScript is not an automated task. The current version is jquery 2.2.4, as the application using my SignalR application was someone bound to this, but I find even this way to old...

P.S.
I would also not have an issue with you forcing me to update an obsolete version of JQuery to the least you expect us to be at...

**Comment by anurse** [comment]
> I would expect information on which JQuery versions can be used, and which ones are advised.

Yes, we would make sure the docs have this information. As far as I can tell, nothing would change here, you could still use any jQuery version above 1.6.4. 

> Are there any known issues with different JQuery versions?

We've tested on the latest version of jQuery (3.3.1) and haven't found any issues, but we don't have the capacity to rigorously test every version. SignalR uses a very core set of jQuery functionality that rarely changes between releases though so generally it has been compatible.

> I would also not have an issue with you forcing me to update an obsolete version of JQuery

I'm sure many people wouldn't mind, but we have a policy about avoiding potentially breaking changes in minor releases. That's the compatibility promise we make ;). Glad to hear you keep things up to date though!

> I hope to be moving to SignalR for ASP.NET Core some time in the near future, but I need dotnet core 3.0 for it (and self hosting) so this is currently not an option.

This isn't directly related to the issue but I have a few questions about this so we can know how to make sure ASP.NET Core works for your scenario:

1. Why do you need .NET Core 3.0? Are you hosting inside a desktop app?
2. Are you aware that ASP.NET Core has full support for self-hosting and is, in fact, self-hosted by default (even when running in IIS, IIS is just proxying to a self-hosted binary)?

**Comment by Lakritzator** [comment]
Hello Andrew, 
thanks for the information!

1. Yes exactly, hosting inside a desktop application. I have designed and build a computer-telephony-integration (CTI) application which runs on the local desktop, and connects a call-center web application which is hosted on a cluster of java application servers with the telephone systems, delivering a full integration making intelligent workflows possible. Due to the requirements (Windows 7), and due the time I started (some time ago, was not priority 1), the application targets .NET Framework (we just updated to 4.7.1) and uses WPF for the small user interaction. Deployment was planed with Click-Once, but currently we need a workaround for some issues we have.
2. Yes I am aware, I really like this! But Core doesn't have UI capabilities, yet! And at this time .NET Core is not yet an accepted runtime on our desktops, so I need to do some lobbying. And to my knowledge, a deployment scenario with a "single" application, is not yet available (?).

I am actually already talking (email / skype) to a couple of your colleagues, among which are: Rich Lander, Bri Achtmann and Daniel Jacobson, the main focus there is using .NET Core 3.0 with Greenshot, which I develop in my spare time. Currently I am working on getting this running on the alphas, but I need some time make the "journey" from .NET Framework to Core. (a lot of packages need updating)

Best wishes
Robin

**Comment by anurse** [comment]
Excellent, glad to hear you're looking to migrate! Yeah, .NET Core 3.0 should bring those desktop workloads up and running for you and Rich and his folks are an excellent source of info for this. Just wanted to check in on the situation there. Looking forward to seeing you over in ASP.NET Core land ;)

**Comment by anurse** [comment]
Given the documentation issues that arise when removing the dependency, I'm not so sure this is a good idea anymore. I'm open to being convinced otherwise, but I'm concerned that we'll get a lot of confused customers installing the package and then getting errors because "jQuery is not defined".
