### ISSUE TITLE
SignalR WMI Counter - Feature Request

### ISSUE THREAD

**Issue by bfriesen0** [SignalR/SignalR#4253]
Hello,

Currently there is a counter called ConnectionsReconnected of type PerformanceCounterType.NumberOfItems32 which tracks total number of reconnections.
I'd like to see a similar counter that tracks reconnections, but of type PerformanceCounterType.RateOfCountsPerSecond32 and called ConnectionsReconnectedPerSec.

I've already written a patch to do this, see attachment, but am unable to open the contributor licence and can't submit a pull request.  Thanks.
[reconnected_counters.zip](https://github.com/SignalR/SignalR/files/2507188/reconnected_counters.zip)

**Comment by anurse** [comment]
> but am unable to open the contributor licence

Is it just that you're having trouble viewing the license or you are unable to sign the license because of your employment contract or corporate policy? We'd certainly welcome a pull request! I can't integrate your changes without a contributor license agreement signed so even distributing it as a ZIP doesn't help here. If it's just that the license agreement isn't loading properly, we can probably figure that out :).

**Comment by anurse** [comment]
You closed the associated PR so I'm going to close this issue. If you're still interested in contributing this, please let me know! We're happy to take the change! The release window for 2.4.0 is closing quickly.
