### ISSUE TITLE
Memory is not correctly reclaimed until the server crashes

### ISSUE THREAD

**Issue by chen950103** [SignalR/SignalR#4288]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
Memory can be reclaimed automatically, and it is stable in a controllable range.
Can I predict memory usage? Suppose the number of connections is 5000.
Is there a memory recovery function?

### Actual behavior
Memory has not been recovered properly, and it keeps growing.

### Steps to reproduce
Production environment
Communication mode: server event.
Microsoft.AspNet.SignalR.Core 2.2.2.0
Run as a service. Not IIS.
Windows Server 2008 R2.
GlobalHost.Configuration.DefaultMessageBufferSize = 32
Each message contains no more than 4000 characters.

Running time: 00:01:00, Memory: 570M, Connection Count: 3370
Running time: 02:00:00, Memory: 1431M, Connection Count: 2700
Running time: 04:00:00, Memory: 1869M, Connection Count: 1700 

Most memory usage: Microsoft. AspNet. SignalR. Messaging. Message
Memory will continue to rise to the upper limit of server memory until the server crashes.
It seems that the memory is not recovered after the user disconnects.

**Comment by clifton-collins3iii** [comment]
I have several memory dumps from our encounter with memory climbing after a network event.  When we stop all of the clients, disconnect and wait for the signalr timeouts, nothing ever happens.  It is like the messages are stuck in a queue with no way to clear and release memory.  It seems that if you are using send.all then the entire group is attempting the reconnect and resend because the memory grows non-linear, increasing in growth each time.

https://pts1-my.sharepoint.com/:f:/g/personal/ccollins_ptssolutions_com/EriJrQTRYyZHkkv5VHSQMjwBoDX8ZT779gNfhvSOmgmSnQ

**Comment by clifton-collins3iii** [comment]
Today we had a client attempt to connect to the signalr-owin server.  The message gets to the server and the server attempts to reply, but cannot, (due to a routing issue).  The client attempts to connect again, because it thinks it never connected because the message from the server never arrived, but the server attempts reconnect, not connect.  This continues until the signalr-owin process consumes all of the memory.  I have been unable to build in a hub monitor to 'shift' the reconnect back to a connect or even better, start blocking/dropping the reconnect and cleaning/releasing memory.  The network issue can be resolved, but signalr should be configurable or at least a method to find stuck messages, remove them and release memory.

**Comment by muratg** [comment]
cc @halter73 @bradygaster

**Comment by halter73** [comment]
The sharepoint link to the memory dump is no longer accessible. Without any details as to which objects we are allegedly leaking, we cannot investigate this further.

**Comment by clifton-collins3iii** [comment]
Understood, since the incident was 23 months a few days ago.

Clifton G. Collins III
225-788-0355
semper quaeritis illi


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
