### ISSUE TITLE
Override JsonSerializer

### ISSUE THREAD

**Issue by larslarsson** [SignalR/SignalR#4298]
Related, is this fixed: https://github.com/SignalR/SignalR/issues/2873

I am confused about how to setup custom json-serializer settings. I cannot override JsonSerializer & getting it to work but I seem to be able to modify the existing, this to me indicates timing issue or signalr simply ignores the overriden one. A note is that the custom contract resolver defined in the json serializer settings is called in the none working scenario but its only called for signalr members/classes & not for my members.

Scenario is self-hosted signalr

Versions
``` 
<package id="Microsoft.Owin" version="4.0.0" targetFramework="net462" />
<package id="Microsoft.Owin.SelfHost" version="4.0.0" targetFramework="net462" />
<package id="Microsoft.AspNet.SignalR.Core" version="2.2.3" targetFramework="net462" />
<package id="Microsoft.AspNet.SignalR.SelfHost" version="2.2.3" targetFramework="net462" />
``` 

``` C#
       public void Configuration(IAppBuilder app)
        {
            var config = new HttpConfiguration();

            this.ConfigureBehaviors(config);
            this.ConfigureSignalR(app);
            this.ConfigureWebApi(app, config);
        }

        private void ConfigureBehaviors(HttpConfiguration config)
        {
            config.Formatters.JsonFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("text/html"));
            var serializerSettings = OwinStartup.JsonSerializerSettings.Value;
            config.Formatters.JsonFormatter.SerializerSettings = serializerSettings;
            //JsonConvert.DefaultSettings = () => { return serializerSettings; };

            // WORKS
            var serializer = GlobalHost.DependencyResolver.GetService(typeof(JsonSerializer)) as JsonSerializer;
            serializer.Formatting = serializerSettings.Formatting;
            serializer.NullValueHandling = serializerSettings.NullValueHandling;
            serializer.ContractResolver = serializerSettings.ContractResolver;

            // Does not work (but if retriving it & manually serializing e.g. inside hub it correct)
            //GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => JsonSerializer.Create(serializerSettings));
        }
```
So many blogs & solutions of how to do it around the web, but does not work.
https://docs.microsoft.com/en-us/aspnet/signalr/overview/advanced/dependency-injection
https://github.com/SignalR/SignalR/wiki/Extensibility#replacing-the-ijsonserializer
https://autofac.readthedocs.io/en/latest/integration/signalr.html#owin-integration

**Comment by bradygaster** [comment]
Is the workaround acceptable? We have no plans at this time to evolve this.

**Comment by larslarsson** [comment]
So this is the expected behavior? Not user error (thats me doing it wrong)?
Guess .net core is where all the goodies & development will be.

**Comment by bradygaster** [comment]
.NET Core is definitely where we are investing most of the improvements and feature work. ASP.NET SignalR is being maintained but trying to maintain feature parity between the two isn't possible.

**Comment by ddweber** [comment]
+1

I´m struggling with an similar issue:
In my case the **JsonSerializer** is injected via depedency injection using **ninject** FW.  I´m trying to use the **CamelCasePropertyNamesContractResolver** but for some reason (i think the same reason @larslarson mentioned) it only works for simple datatypes/classes. It does not work for dataTables, there the DefaultContractResolver seems to be used.

**Comment by ddweber** [comment]
@bradygaster Any further ideas/hints on how to workaround this behaviour? It´s blocking my deployment since clientside scripts expect data to be in camleCase (default in javascript).

**Comment by bradygaster** [comment]
Is the issue that your JavaScript **must be** in `camelCase` and SignalR/ASP.NET is serializing as `PascalCase`? If none of the above methods have worked in tweaking the casing, and using `HubName` and/or `MethodName` attributes are also not working, I am unsure what to do. cc @jamesnk

**Comment by ddweber** [comment]
Not quite.
The problem is that the **data** which is send to the clients **must be** in `camelCase` but SignalR/ASP.NET is serializing it as `PacalCase` when the data is of the `DataTable` type. For a simple object like the instance of a user-build class the camelCase-serialization works perfectly.
The `HubNames` and `MethodNames` are all allright too.

Let me explain my background a bit futher:
I´m working on a [stocker-ticker](https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-server-broadcast-with-signalr) like application which broadcasts/sends data to the connected clients. Clientmapping is held in memory like in [this example](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#in-memory-storage). All is tied together via [dependeyInjection](https://docs.microsoft.com/en-us/aspnet/signalr/overview/advanced/dependency-injection#using-ioc-containers-in-signalr) IoC Containers/ninject and the JsonSerializerSettings (including the ContracResolver) get managed like in [this](https://stackoverflow.com/questions/30005575/signalr-use-camel-case).

Sending data to clients/invoking client-methods with data is done like this:
```csharp
IClientProxy proxy = Clients.Client(connectionId);

// WORKS
ChatMessage chatMessage = new ChatMessage { Message = "Hello", User = "ddweber" };
proxy.Invoke("addChatMessage", chatMessage );

// DOES NOT WORK
DataTable dataTable = ... //(get from SQL)
proxy.Invoke("methodName", dataTable);
```

While debugging i can see that the **CamelCasePropertyNamesContractResolver** resolves the Contract (JsonISerializableContract) for the `DataTable` type, but the output is still in `PascalCase`.

Thanks for your response and sorry the amount of links, but copying all in here would be a lot to read.

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).

**Comment by larslarsson** [comment]
Would be more clear to say "will not fix" - the original post is about setting json serializer setter does not work since a reference to the original is taken another part of the code thus only way to actually override correctly is not setting the json serializer but overwriting its properties i.e. copy all properties. Back then not documented & a strange behavior / documentation seemed to indicate that it should work. Or it has been changed but I doubt it since seems only .core is updated with non critical changes.
