### ISSUE TITLE
Signalr connection issue in Visual Studio Load Test

### ISSUE THREAD

**Issue by syedharishassan** [SignalR/SignalR#4309]
I am trying to run load test on my application containing signalr. When I run the application, all its requests get recorded. My app runs smoothly till this point. But when system runs my application through the recorded session then it is throwing an error on "Signalr/connect" method. It says, connectionId is invalid. 

I didnt call "signalr/connect" method directly. I just called "$.connection.hub.start();" in my javascript. "connect" call is signalr internal call which is expecting a connectionId.

How can I resolve this issue?

**Comment by bradygaster** [comment]
This tool isn't designed for long-running connections and we'd discourage you from using it to test SignalR.

**Comment by syedharishassan** [comment]
> 
> 
> This tool isn't designed for long-running connections and we'd discourage you from using it to test SignalR.

Are you talking about visual studio load test tool? I am not testing signalr. I am testing my application but signalr is a bottleneck. Please guide me.

**Comment by halter73** [comment]
You cannot use normal web perf test tools on signalr because responses take a long time by design. You need to do custom testing to ensure clients get messages in a timely manner.

If you're load testing other endpoints, look at the loadtest tool's config and see if the /signalr endpoint can be disabled.
