### ISSUE TITLE
[Azure SignalR] Disable automatic reconnects

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#4317]
SignalR's automatic reconnect functionality does not redo a negotiate request which is necessary for reestablishing a connection to the SignalR service. For this reason, we should disable the automatic reconnect functionality when connected to the service. This is a follow up to #4284.

**Comment by vicancy** [comment]
Hi Halter, after revisiting this issue, I feel that /reconnect can still be useful when handling cases when physical connections slow or interruptions in connectivity.

For the following cases, I think Azure service might need to document the expect behavior and encourage users to add "restart" logic as stated in [How to continuously reconnect](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#how-to-continuously-reconnect):
1. When One App Server closes, the Azure Service closes the client connection proactively by sending `{"E": "Server offline"}` error message. In this case, the latest client already stops /reconnect, as https://github.com/SignalR/SignalR/issues/4197#issuecomment-428765556 indicates
2. When Azure service restarts, current client behaves as /reconnect several times and fails with 404 because the connectionId no longer exists in the Azure service. This is the case we discussed before and wonder if disabling /reconnect can help.

cc @davidfowl @chenkennt

**Comment by halter73** [comment]
@vicancy If we allow the old clients automatically reconnect to the service, is it possible that messages intended for the reconnecting client could be missed during the reconnect? If messages could be missed, I don't think it's a good idea to allow automatic reconnects to the service as that would break customer expectations.

Making automatic reconnect functionality an opt-in feature when connected to the service could be a way to offer automatic reconnects without breaking expectations, but I'm concerned even that could create more work that will push back a 2.4.1 patch if the reconnect logic has to work differently when connected to the service.

The old SignalR clients do not redo /negotiate requests when automatically reconnecting. Would this be necessary for reconnecting to the service? If the clients do have to renegotiate when automatically reconnecting to to the service, that would require rewriting the reconnect logic for both the JavaScript and .NET clients.

**Comment by vicancy** [comment]
> Is it possible that messages intended for the reconnecting client could be missed during the reconnect?

Yes, Azure Service does not replay message so messages during this period will be missed. I am wondering if a well-documented "Breaking changes when migrating ASP.NET applications to Azure Service" can address a proper expectation instead of just disabling it.

> The old SignalR clients do not redo /negotiate requests when automatically reconnecting. Would this be necessary for reconnecting to the service?

We can keep the current behavior for "reconnect" that it does not redo /negotiate. Users are encouraged to add "restart" logic as stated in [How to continuously reconnect], "restart" will redo /negotiate.
