### ISSUE TITLE
Weird behavior with groups on Firefox and google chrome, works ok on edge..

### ISSUE THREAD

**Issue by Worlddue** [SignalR/SignalR#4327]
Please remove this line and the line above before submitting a new issue.

I am imitating linked in with posts and comments, I want to use signalr to automatically update the comment section, so I created a group added each user that will go to his news feed page, and when anybody starts to type a comment a front end js will fire sending the poster id and the post id to the hub and then the hub will filter out each friend/user that can see this post using the group and then it will push the new update here is my hub code:

```
public void AnnounceComment(int postId, string postUserId)
        {
            string userID = Context.User.Identity.GetUserId();

            var owner = u.context.Users.Include(u => u.Friends).Where(u => u.Id == postUserId).FirstOrDefault();

            var idList = owner.Friends.Select(f => f.FriendUserID).ToList();

            idList.Add(postUserId);

            Clients.OthersInGroups(idList).AnnounceComment(postId);
    } 
```

and my on connected is as follows:

```
public  override Task OnConnected()
        {
            string name = Context.User.Identity.GetUserId();

             Groups.Add(Context.ConnectionId, name).Wait();

            return base.OnConnected();
        }
```

my front end:

```
$.connection.hub.start()
    .done(function () { })
    .fail(function () { alert("ERRORRR!!!!!") })

//From client to server talking to it.
function signalrAnnounce(postID,op) {
    $.connection.linkedInHub.server.announceComment(postID,op);
}

$.connection.linkedInHub.client.announceComment = function (message) {

    alert(message);
}
```

### Actual behavior: It doesn't filter out anything and sends data to everybody.

**Comment by halter73** [comment]
Are you positive your `idList` in AnnounceComment does include "everybody"?

As an aside, you don't need to add the connection to a single-user group matching its user id on OnConnected. You can use `Clients.User(userId).AnnounceComment(postId)` instead. By default, a client's user id will be pulled from `IPrincipal.Identity.Name`, but you could change this to use `IPrincipal.Identity.GetUserId()` if that's any different. You can find out how to do that in the following guide: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#iuserid-provider

Even if you do need to use groups instead of a user id, you should await `Groups.Add` instead calling `Task.Wait()`.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
