### ISSUE TITLE
SignalR and HTTP/2

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4330]
I can't seem to find any articles/information/clarification on how SignalR works with HTTP/2 (the protocol is included in IIS 10 which has been out for a while now).

Does SignalR use HTTP/2 as a new transport? Or does it simply fall back to other transports? Or keeps using WebSockets? (the latter seems not to be the case, since I don't see any WS connections when using signalr with an http/2-enabled server)

**Comment by anurse** [comment]
ASP.NET SignalR doesn't have any specific HTTP/2 support. The Long Polling and Server-Sent Events transports will be somewhat optimized by HTTP/2 "for free" if your browser and server support it because they will use HTTP/2 for their requests. However, as you noted, WebSockets are not supported over HTTP/2, so they always use HTTP/1.1

We don't have any plans to add any HTTP/2-specific enhancements to ASP.NET SignalR at this time.

**Comment by wilvermelendez** [comment]
Hello @anurse , Is there any update about this or it is still the same?

**Comment by anurse** [comment]
It's about the same. We still don't have plans for an HTTP/2-specific transport, but the existing transports should work fine. Do you have needs that aren't currently met by the current set of transports?

**Comment by alex-jitbit** [comment]
@anurse yes, because most browsers have limits on the number of connections per domain to 4-10. For example Chrome has 6 simultaneous connections limit. **Which means you can't open the same app in more than 4 tabs** everything freezes and stops working.

Websockets do not have this limit.

**Comment by anurse** [comment]
Right, but simply using HTTP/2 with the *existing* transports removes that limitation. Or, using WebSockets. There are no changes needed to SignalR to _support_ HTTP/2. Are you seeing this issue (limited connections) when running SignalR on a server and client that supports HTTP/2?
