### ISSUE TITLE
OnConnected doesn't fire on the server to which the client is actually connected

### ISSUE THREAD

**Issue by wluke** [SignalR/SignalR#4341]
I'm using across a farm of servers with a Redis backplane. Requests are load balanced using IIS ARR. New requests could hit any server in the farm. I need to track which server each client is actually connected to (eg which server it's SignalR websocket connection goes to)

### Expected  behavior
When OnConnected is called, I can check the server and store that.

### Actual behavior
OnConnected is called but this is on a different server to the one the client is actually connected.

**Comment by halter73** [comment]
This is by design. OnConnected fires on whatever server receives a "/start" request from the client. This server could be different from the server which ultimately handles the client's "/(re)connect" request and is responsible for sending data to said client.

If you want to ensure OnConnected fires on the server which the client is connected, I recommend using sticky sessions.
