### ISSUE TITLE
Signal R is not working in safari, When I change my environment to Client(USA) fom my env(IND).

### ISSUE THREAD

**Issue by Nagavijay-kolla** [SignalR/SignalR#4356]
I am working with safari 1v, I have developed a chat app, it is working very well in all browsers in my environment but when I push the code to TFS  and deployed it in client environment. Here , In safari, SignalR connection is not happening - negotiate is not happening

but in my environment it is working in all browsers, if I access client hosted URL it is not working in safari. 

I know this is hard to understand from the above explanation but please give me a suggestion or any solution to resolve it. Please help me.

Thanks in advance.

**Comment by anurse** [comment]
Do you get any errors in the browser console?

Can you enable client-side tracing on the browser (using the guide [in our documentation](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-in-the-javascript-client)) and share logs with us by attaching them to the GitHub issue (drag-and-drop a text file on instead of pasting the content please). We need to understand how it is failing.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
