### ISSUE TITLE
"Connection started reconnecting before invocation result was received"

### ISSUE THREAD

**Issue by rajeevBlr** [SignalR/SignalR#4378]
@davidfowl please help with this issue. I am using Microsoft.AspNet.SignalR 2.4.1 and Microsoft.AspNet.SignalR.Client 2.4.1

I am invoking method on HubProxy within WebAPI controller API.

public async Task SaveNew([FromBody]InputParameter inputParameters) { 
             await hubProxy.Invoke("Method", inputParameters); 
}

At times I get 'Connection started reconnecting before invocation result was received' error message.

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at SignalR.UpdateNotifier.d__7.MoveNext() in D:\XXX\Source\APP\src\WEBAPI\SignalR\ABC.cs:line 79
--- End of stack trace from previous location where exception was thrown ---

**Comment by anurse** [comment]
This is by-design behavior. If the connection drops while you still have an invocation outstanding, this error is thrown so that you can catch it and know that the server **did not complete** this invocation. That way you can choose to retry it. As always, be aware that the server may have actually finished executing but crashed or lost network connectivity before the response could be sent, so when retrying you should make sure the server behavior doesn't repeat the completed operation.

**Comment by rajeevBlr** [comment]
@anurse thanks for the response.
Upon Invoke when a list of objects with of count > 50 is sent, then this error comes. When I send list with a single object in it then this error does not occur. 

So could this be an issue with the size of data which is being pushed via the 'Invoke' method?

I attempted by increasing Client to server web socket data by setting  MBMaxIncomingWebSocketMessageSize to > 10 MB. Still no luck.

**Comment by anurse** [comment]
It should only be an issue if the connection is disrupted **during** the invocation. The size of the message should only matter in that it takes longer to process and thus may be more likely to get hit by a network interruption.

Can you enable client-side tracing (see docs here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing) and see if you get any log messages about reconnecting when this happens?
