### ISSUE TITLE
SignalR client leaks connections when server is down

### ISSUE THREAD

**Issue by mottagare** [SignalR/SignalR#4412]
I am hosting an AspNet SignalR Client (Microsoft.AspNet.SignalR.Client.dll v2.4.1) in an Azure AppService app. It connects to a SignalR server that I do not control. This server sometimes reboots or are down for maintenance. When this happens the number of outgoing connections quickly hits the limit of an AppService app (>1000). The connections are not freed up until I reboot the app. See screenshot of connections. 
<img width="957" alt="signalr_connections" src="https://user-images.githubusercontent.com/4429184/65858886-52b15200-e367-11e9-9f7b-d83d605a8194.png">

Is there a way for me to handle this scenario or is it an issue with the aspnet signalr client?

Log attached (I have removed tokens etc) 
[signalrclient.txt](https://github.com/SignalR/SignalR/files/3669416/signalrclient.txt)

**Comment by anurse** [comment]
From the logs it looks like the clients are in a loop trying to reconnect, which could explain the spike in connections. Spiking to over 1000 seems curious though, unless you have a large number of client connections in place. How many server instances do you have and how many instance of the client do you have on each server?

What is the stable number of connections in your app?

**Comment by halter73** [comment]
Thanks for the logs. That proved useful when tracking down the cause of this issue.

The first thing that was apparent from the logs is that the client entered a double-reconnect-loop where the WebSocketTransport's [DoReconnect()](https://github.com/SignalR/SignalR/blob/61c1a688f6a4e714e43c5b82b10f6d8b7c612dd6/src/Microsoft.AspNet.SignalR.Client/Transports/WebSocketTransport.cs#L167-L194) loop was running twice in parallel for the same connection. This means every time there should have been one /reconnect request, there were two.

Exacerbating the problem is that when the second /reconnect request comes in for the same connection id, the server kicks the first /reconnect request by aborting the request causing one of the reconnect loops to continue. Ultimately, each time a reconnect attempt succeeds, it immediately induces another reconnect attempt, and this continues indefinitely 😢

How did we end up in a state where 2 DoReconnect() loops are running simultaneously in the first place? I have theory. I think the client from the logs had already successfully reconnected once meaning that there was a still-incomplete call to DoReconnect() from the *last* reconnect when another reconnect started. This can happen, because PerformConnect() counterintuitively doesn't actually complete until the connection closes instead of completing as soon as a connection is established like you may assume from the name "PerformConnect".

After the connection stops the second time, the client unsuccessfully [attempts to start a close handshake](https://github.com/SignalR/SignalR/blob/61c1a688f6a4e714e43c5b82b10f6d8b7c612dd6/src/Microsoft.AspNet.SignalR.Core/Owin/WebSockets/WebSocketHandler.cs#L227) which ultimately causes PerformConnect() to throw continuing the first DeReconnect() loop. At the same time the finally block [triggers another OnClose() callback](https://github.com/SignalR/SignalR/blob/61c1a688f6a4e714e43c5b82b10f6d8b7c612dd6/src/Microsoft.AspNet.SignalR.Core/Owin/WebSockets/WebSocketHandler.cs#L236) which can be seen in the logs. This OnClose() callback is what triggers the second DoReconnect() loop.

Thanks again for the bug report.

**Comment by mottagare** [comment]
Thanks for the update and investigation into the issue @halter73 

@anurse The logs are from a single instance out of 2 available. Same thing have happened using only 1 instance. Normally an instance have about 10 connections.
My code does a reconnect on the "Closed" event, but my application logs show that only occurred once during the time period of the connection logs attached in the original post.

**Comment by anurse** [comment]
> My code does a reconnect on the "Closed" event

Could you share some of this code? Basically how you handle the closed event and trigger the reconnect. If you need to redact some confidential information and trim some irrelevant code that's OK, but we'd appreciate clarifying what that removed code does in a comment or something. If necessary, we can also provide a mechanism to share code privately.

**Comment by anurse** [comment]
Sounds like @halter73 has identified a possible issue here and we'll be looking at this for 2.4.2 (release date TBD, likely by end of 2019).

**Comment by vicancy** [comment]
Hi @halter73 So this issue sounds not restricted to WebSocket reconnect, but also SSE and LongPolling, right?

**Comment by halter73** [comment]
@vicancy This issue *is* restricted to WebSocket reconnect. I suppose it's possible there's similar bugs in SSE and LongPolling, but I haven't seen it. Have you seen issues like this with the other transports?
