### ISSUE TITLE
Upgrade from 2.3.0 javascript client to 2.4.1 causes cookies to be lost when making a request on a different port

### ISSUE THREAD

**Issue by robertpi** [SignalR/SignalR#4413]
I have an web app hosted on port 9358, for various reasons this web uses signalr instance that is hosted on port 9359. The app relies on a cookie for authentication, in version 2.3.0 this cookie is included in the request to signalr, in 2.4.1 it is not. Profiling with fiddle allows me to see the changes in the request.

### Request from version 2.3.0

```
GET http://localhost:9359/web/api/signalr/negotiate?clientProtocol=1.5&_=1570024705111 HTTP/1.1
Host: localhost:9359
Connection: keep-alive
Accept: text/plain, */*; q=0.01
Origin: http://localhost:9358
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 OpenFin/10.66.39.43 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://localhost:9358/web/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: rfqweb-connection-guid=72dd1f86-d656-42b5-99f8-7e1f7d50cfbd
```

### Request from version 2.4.1

```
GET http://localhost:9359/web/api/signalr/negotiate?clientProtocol=2.1&_=1570023046857 HTTP/1.1
Host: localhost:9359
Connection: keep-alive
Accept: text/plain, */*; q=0.01
Origin: http://localhost:9358
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 OpenFin/10.66.39.43 Safari/537.36
Content-Type: application/json; charset=UTF-8
Referer: http://localhost:9358/web/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

Why has this behaviour changed? Is there anyway 2.4.1 can be configured to include the cookies as 2.3.0 does?

**Comment by anurse** [comment]
I'm not aware of any behavioral change (certainly not an intentional one). Can you try forcibly enabling cookies using the following code in your `.start` call:

```javascript
$.connection.hub.start({ withCredentials: true });
```

That setting controls the sending of cookies for cross-domain requests. By default, we default to `true` (unless you explcitly set it to `false`), so this should be unnecessary, but perhaps something in our cross-domain detection logic broke.

Could you also enable tracing in the JavaScript client as well and capture browser console logs to post here? (see https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-in-the-javascript-client for details on enabling this).

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
