### ISSUE TITLE
aspnet/signalr is adding token as query parameter

### ISSUE THREAD

**Issue by ansh-carrier** [SignalR/SignalR#4418]
# Expected  behavior
Is there a way that token can be added as a part of header instead of query string?
### Actual behavior
API is appending token as query parameter.
### Steps to reproduce

Currently we are using @aspnet/signal version 1.1.2 with Angular 7.0.3
Package.json entry:
"@aspnet/signalr": "^1.1.2"

Angular Code for staring connection:

public startConnection = () => {
    this.userDetails();
    const token = this.getToken(this.loggedInUserEmail);
    const options = {
        transport: signalR.HttpTransportType.ServerSentEvents,
        logging: signalR.LogLevel.None,
        accessTokenFactory: () => token,
    };
    this.hubConnection = new signalR.HubConnectionBuilder()
        .withUrl(this.url + '&users=' + this.loggedInUserEmail, options)
        .build();
    this.hubConnection.serverTimeoutInMilliseconds = 9999999999999;
    this.hubConnection.on('AppNotifications', (data: any) => {
      data = JSON.parse(data);
      console.log('notification data:', data);
    });
    this.hubConnection.start();
  }

The above code is working absolutely fine.
But when view in chrome developer window's network tab, access key is attached along with the GET request URL.
This is identified as a cyber-security threat.
Is there a way that this can be added as a part of header instead of query string?

Request URL: 

https://xyz.signalr.net/client/?hub=UnoAppNotificationHub&users=<user-id>&id=abc&access_token=some-tough-token

**Comment by BrennanConroy** [comment]
We make a best effort to put the auth token in a header, unfortunately due to browser API limitations there are some places we have to fallback to a query string. Specifically [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) for ServerSentEvents and [WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) for WebSockets.

In the future please file issues for aspnet/signalr or Microsoft.AspNetCore.SignalR.* in https://github.com/aspnet/AspNetCore/issues

**Comment by anurse** [comment]
Closing as the question has been answered. As per @BrennanConroy 's comment, if you still have questions about **ASP.NET Core** SignalR, they should be filed in https://github.com/aspnet/AspNetCore/issues
