### ISSUE TITLE
net45 SignalR does not support WebSocket when using Azure SignalR

### ISSUE THREAD

**Issue by vicancy** [SignalR/SignalR#4435]
It's caused by:
https://github.com/SignalR/SignalR/blob/0ba22650e6eb1e4e4bf523c70951952a559db65d/src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs#L77-L81, for `net45` version, it checks inside the redirect response from Azure SignalR that if it contains `TryWebSockets` in the redirect response which of cause not.

Easy to repro: Create a Console App under `net45`, install SignalR client package, and connect to app server which enables AzureSignalR. WebSocket transport is always excluded.

Is it a bug or by design?

**Comment by anurse** [comment]
Sounds like a bug (per discussion offline with @davidfowl). @halter73 can you take a look? It sounds pretty reliable to repro, it's likely to be an issue with how we handle the redirect.

**Comment by halter73** [comment]
I was able to reproduce this issue with a .NET 4.7.2 client. Interestingly, because the ifdef doesn't include `|| NETSTANDARD2_0` like it should, you can work around the issue by targeting .NET Core 2.0 or later. I get that most customers targeting full framework are doing so because they cannot migrate to full framework.

I'm going to look into a workaround that involves replacing the AutoTransport with a custom version. I don't think we will be able to actually patch the client until January at the earliest due to the holidays.

**Comment by halter73** [comment]
@vicancy @anurse Can either of you give me push access to https://github.com/aspnet/AzureSignalR-samples? Thanks.

**Comment by anurse** [comment]
@halter73 done. Not sure why `aspnet-push` only had read access :).
