### ISSUE TITLE
Does it support non-session stick connections ?

### ISSUE THREAD

**Issue by jerry153fish** [SignalR/SignalR#4561]
Hello, we are using SignalR to send back notifications to the front-end with wss. For now, we are using round-robin in our service. We had to enable session affinity to get it working correctly.

We had cache the session back on redis, is there any way to generate same connection id on every instance instead of enable session stick ?

**Comment by halter73** [comment]
I'm not sure exactly what problem you were originally running into without sticky sessions, because that's supported with this version of SignalR if you're using a scaleout provider like Redis (I'm assuming you're not using ASP.NET Core).

Do you have more details about what went wrong with round-robin load balancing? It can be trickier for the app to deal with invocations from the same client arriving on different servers if the app has any in-memory state. But if you avoid that, it shouldn't be a problem.
