### ISSUE TITLE
Connection started reconnecting before invocation result was received

### ISSUE THREAD

**Issue by eeldivad** [SignalR/SignalR#4607]
I'm running ASP.NET SignalR 2.4.2, not .Net core.  Error is:  Connection started reconnecting before invocation result was received.

I'm getting this error for users on the other side of the world but it works fine for me locally.  It only happens when sending large amounts of data through signalR for users in other countries.  It's probably in the megabytes.  I've disabled the size limits so that's not the issue.  If they choose a smaller data set to retrieve then it works fine.  So it seems to be some kind of timeout for waiting too long since it takes longer to transfer that much data across the world.  I read somewhere that it's due to signalR trying to reconnect and interrupts the data transfer.  I don't think it's that the network has issues.  It's just that it takes more than 20 seconds to transfer all the data across the world.  Is there a way to increase the time that signalR thinks there's a network issue and tries reconnect?  I think it's somewhere between 10-15 seconds by default.  It would be better if signalR was smart enough to know that data is in transit and its receiving them in chunks and not disrupt the connection before the transfer is complete.

**Comment by halter73** [comment]
> It's just that it takes more than 20 seconds to transfer all the data across the world. Is there a way to increase the time that signalR thinks there's a network issue and tries reconnect?

This does seem likely. If it takes more than 10 seconds to transmit a message under normal circumstances, we recommend redesigning the app to chunk up the data into smaller pieces manually. This allows SignalR to confirm the connection is alive by verifying it receives a message at least once every 20 seconds.

If you must send larger message, you can try increasing the [DisconnectTimeout](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#disconnecttimeout) to something larger than 30 seconds. Fo example, if you increase it to 60 seconds, SignalR will send a keep-alive message every 20 seconds instead of every 10 seconds. The downside is that the client will only start reconnecting after 40 seconds instead of 20 seconds when there really was a network issue. And the server won't call the Hub's `OnDisconnected(bool stopCalled)` method until 60 seconds after the first failed attempt to send a message to the client instead of the default 40 seconds.
