### ISSUE TITLE
SignalR and Redis backend with ACL

### ISSUE THREAD

**Issue by ElCheekytico** [SignalR/SignalR#4661]
It doesn't appear that this supports connecting to Redis with ACL implemented. What are the options or will this be implemented?

**Comment by BrennanConroy** [comment]
Add a newer reference to https://www.nuget.org/packages/StackExchange.Redis and set the user in the configuration settings. This isn't something that SignalR implements, it's the underlying Redis library that adds support for ACL, which it does since ~March 2020 https://github.com/StackExchange/StackExchange.Redis/pull/1410.
