### ISSUE TITLE
SignalR Configuration On Proxy DNS Server For NGINX

### ISSUE THREAD

**Issue by KuldeepSinghAdaptit** [SignalR/SignalR#4690]
Good Morning

I am Facing Issue in SignalR Configuration , Let me Explain

My Functionality Work Perfectly In Dev & UAT Environments But it's Not Working On Production, Client Use Private/ Public DNS For Showing Application & We are using NGINX For Hosting.

Firstly I thought I make Multiple Hub URL & It's Resolve My Issue But Not.

Please Kindly Suggest Any Process Or Configuration For Resolving This.

Thanks Kuldeep Singh

I Got this Solution https://docs.wallarm.com/admin-en/configure-dynamic-dns-resolution-nginx/

But this one Is Paid

**Comment by BrennanConroy** [comment]
You haven't actually said what your issue is...
Regardless, we aren't a generic forum for Nginx configuration, try a public forum like stackoverflow.

You can also take a look at our rough nginx guidelines and see if you're missing something
https://learn.microsoft.com/aspnet/core/signalr/scale?view=aspnetcore-7.0#linux-with-nginx
