### ISSUE TITLE
Callback function in javascript not getting called

### ISSUE THREAD

**Issue by ssmidnight** [SignalR/SignalR#636]
I have recently started learning SignalR and found some example applications that I used as a guide for my own implementation. However, I cannot seem to get the callback javascript function to execute.

On the server side inside my hub class, I set a breakpoint in the "Echo" method that gets hit, however, when I try to call the "newMessage" callback function, my alert in the page never fires. I have researched for this for a couple of days now on my own with no solution. I really hope you can help me find what I am doing wrong. I have included the client and server side code for a simple test app I put together to try and nail down the issue, with no success yet.

Thanks,
Shay

Here is my client side code:

```
var client = null;

$(function () {
    client = $.connection.appHub;

    $.connection.hub.start(function () {

        client.newMessage = function (message) {
            alert(message);
        };
    });

    $("#Send").click(function () {
        client.echo($("#SendEcho").val());
    });
});
```

Here is the server side code:

```
namespace TestSignalR
{
    [HubName("appHub")]
    public class TestHub : Hub
    {
        public void Echo(string message)
        {
            Clients.newMessage(message);
        }
    }
}
```

**Comment by B6692** [comment]
Hi David,
I know this issue has been treated before since I have googled and read most of the responses of people who have had the same or similar problem in the past. The problem I have is my client method is not getting called and I have already defined the client method before starting the hub. When I do that I get another error but when I define the method after starting my hub, I don't get an error but then my client function does not fire.

I think, the fact that I am self-hosting in a Win service or because I am using AngularJS, that's why I am having this problem. but I am not really sure.

Can you help me? Any suggestions? Of course I have gone through the SignalR troubleshooting guide several times. I have checked the name of my client method to make sure all is correctly named but still this problems rears it head. I would like to believe the fact that its because I am self hosting or because of Angular . I get the following error when I debug using Chrome: **jquery-2.2.1.js:9175 GET http://localhost:36900/OffiGestion/start?transport=serverSentEvents&clientP…D%3D&connectionData=%5B%7B%22name%22%3A%22offihub%22%7D%5D&_=1459195567970 500 (Internal Server Error)**

In case you wish to see my code, here it is:      
       var offiHub = $.connection.offiHub;
        offiHub.client.publishSales = function (so) {
            //Add to the current list.
            console.log("We got here!");
            log('We got here, hurray!.');
       };
   
        $.connection.hub.start().done(init);
