### ISSUE TITLE
I can only have about 6 tabs open to my SignalR app.

### ISSUE THREAD

**Issue by BeekeeperAlex** [SignalR/SignalR#807]
We implemented SignalR to build a real-time notification system that would warn users when a new release of the website was about to happen. It works beautifully. The only thing I didn't realize was that users of our site open many tabs while examining our data. They can only have about 6 concurrent connections to our website. After 6 tabs additional tabs will simply sit and spin with no response from the server.

I found this video of someone with the same issue.
http://www.youtube.com/watch?v=yRGBHeMKlmI&feature=youtu.be

This appears to be a browser limitation. Is there any suggestions for how to work around this? Is there a way to detect how many connections they have? The easy solution that I can see is to simply limit the number of SignalR connections to about 3, leaving the remainder of allowed connections to service plain web and ajax requests. When the page loads I'd need to know how many connections that user currently has and forgo starting up a hub connection.

Any help is appreciated.

**Comment by PolloKulos** [comment]
Hi, I have the same error, when opening several tabs they no longer load completely, any idea Please?

**Comment by anurse** [comment]
Which transport are you using? If you are **not** using WebSockets, browsers limit the number of concurrent HTTP connections to a single domain to 6 and each SignalR connection will take up one of these. That means that after establishing 6 SignalR connections, future connections will fail (this includes non-SignalR HTTP requests). This is a limitation of the browser and not something SignalR can prevent.

The recommended solution for this is to move your SignalR traffic to a different domain/subdomain.

**Comment by PolloKulos** [comment]
Hi, use SignalR, WebSockets, but I want only one tab to use signalr, is there a way to block that in other tabs?

**Comment by PolloKulos** [comment]
Hi, use SignalR, WebSockets, but I want only one tab to use signalr, is there a way to block that in other tabs?

**Comment by anurse** [comment]
SignalR doesn't provide such a mechanism. It would be up to your app to prevent the other tabs from connecting if it were something you wanted to prevent.

**Comment by PolloKulos** [comment]
I only need to use signalR in a tab, but when I open other tabs they do not load completely and I do not want to use that technology. Any 
suggestion?

**Comment by anurse** [comment]
> but when I open other tabs they do not load completely and I do not want to use that technology

This sounds like the underlying problem. If you're using WebSockets things should load properly. What fails to load? Can you use the Network tab in your browser dev tools to find out what requests are failing?

**Comment by PolloKulos** [comment]
Can you use the Network tab in your browser dev tools to find out what requests are failing?

The message display in network tool:

Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See https://www.chromestatus.com/feature/5527160148197376 for more details.

This error only in Chrome, in IE working fine.
 In the new tab open Chrome, have 3 iframes and 3 higcharts, this can cause signalR to fail?

**Comment by anurse** [comment]
Yes, that is the error that indicates you have too many active connections. However, a SignalR WebSocket connection should not contribute to this limit. Do you have any network requests that show as "(pending)" in the network tab?

> In the new tab open Chrome, have 3 iframes and 3 higcharts

That would depend on what content you have in the frame and how many pending HTTP requests they have.

The browser only permits 6 **active** HTTP connections to be made to the same domain name. If there are already 6, then you have to wait for one of them to complete before you can start another. This affects SignalR's *long polling transport* because it works via a long-running HTTP request, but WebSockets should not be affected.

Could you save a HAR file from the network tab? You can do this by right clicking on any of the requests and choosing "Save as HAR with content". It will save all the requests, you don't have to do it for each request in the list. Please **attach** the file (do not just paste the content) by dragging and dropping it on to the comment box in GitHub (you may need to rename it to end `.txt` in order to upload it)

> This error only in Chrome, in IE working fine.

Yes, each browser has different limits so this is somewhat expected.

**Comment by PolloKulos** [comment]
> Yes, that is the error that indicates you have too many active connections. However, a SignalR WebSocket connection should not contribute to this limit. Do you have any network requests that show as "(pending)" in the network tab?

-Yes i have more of 100 request (pending).


Example request pending:
[example.txt](https://github.com/SignalR/SignalR/files/2447467/example.txt)

**Comment by anurse** [comment]
That's a lot of pending requests, none of which seem to be SignalR related. And all of these are listed as "(pending)" for you? That would cause this problem then, it's not related to SignalR specifically.

**Comment by PolloKulos** [comment]
> And all of these are listed as "(pending)" for you? 

Yes, all list is ("pending")
